export const products_json = [
  {
    id: "1",
    code: "VET-001",
    name: "Antiparasitario Interno Canino",
    description: "Comprimidos para el control de parásitos intestinales en perros.",
    category: "Medicamentos",
    stock: 15,
    minStock: 6,
    price: 22.50,
    costPrice: 14.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "2",
    code: "VET-002",
    name: "Alimento Seco Premium Gatos Adultos",
    description: "Fórmula equilibrada para gatos adultos con ingredientes de alta calidad.",
    category: "Alimento",
    stock: 30,
    minStock: 4,
    price: 45.00,
    costPrice: 30.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "3",
    code: "VET-003",
    name: "Collar Antipulgas y Garrapatas Perro Grande",
    description: "Collar de larga duración para protección externa.",
    category: "Antiparasitarios",
    stock: 10,
    minStock: 8,
    price: 35.00,
    costPrice: 21.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "4",
    code: "VET-004",
    name: "Champú Hipoalergénico para Perros",
    description: "Champú suave formulado para pieles sensibles.",
    category: "Higiene",
    stock: 18,
    minStock: 5,
    price: 15.75,
    costPrice: 9.50,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "5",
    code: "VET-005",
    name: "Juguete Pelota Resistente Morder",
    description: "Pelota duradera para juegos y ejercicio.",
    category: "Juguetes",
    stock: 25,
    minStock: 7,
    price: 10.99,
    costPrice: 6.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "6",
    code: "VET-006",
    name: "Suplemento Vitamínico Canino",
    description: "Complejo de vitaminas y minerales para perros.",
    category: "Vitaminas",
    stock: 12,
    minStock: 4,
    price: 18.00,
    costPrice: 11.00,
    supplier: "Laboratorio Nutrición D"
  },
  {
    id: "7",
    code: "VET-007",
    name: "Snacks Dentales Gatos",
    description: "Snacks que ayudan a reducir el sarro y el mal aliento en gatos.",
    category: "Cuidado Dental",
    stock: 40,
    minStock: 6,
    price: 8.50,
    costPrice: 4.50,
    supplier: "Marca PetFood Y"
  },
  {
    id: "8",
    code: "VET-008",
    name: "Limpiador de Oídos para Perros y Gatos",
    description: "Solución suave para la higiene regular del conducto auditivo.",
    category: "Cuidado Ocular/Otico",
    stock: 20,
    minStock: 5,
    price: 12.00,
    costPrice: 7.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "9",
    code: "VET-009",
    name: "Transportadora Rígida Gato/Perro Pequeño",
    description: "Transportadora plástica segura y cómoda.",
    category: "Accesorios",
    stock: 8,
    minStock: 4,
    price: 30.00,
    costPrice: 18.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "10",
    code: "VET-010",
    name: "Arena Sanitaria Aglomerante Gatos",
    description: "Arena de alta absorción y control de olores.",
    category: "Higiene",
    stock: 50,
    minStock: 8,
    price: 14.50,
    costPrice: 9.00,
    supplier: "Marca Arena F"
  },
  {
    id: "11",
    code: "VET-011",
    name: "Antiparasitario Externo Pipeta Gato",
    description: "Pipeta spot-on para pulgas y garrapatas en gatos.",
    category: "Antiparasitarios",
    stock: 17,
    minStock: 5,
    price: 28.00,
    costPrice: 17.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "12",
    code: "VET-012",
    name: "Alimento Húmedo Terapéutico Renal Canino",
    description: "Alimento húmedo formulado para perros con enfermedad renal.",
    category: "Alimento Terapéutico",
    stock: 9,
    minStock: 4,
    price: 3.50,
    costPrice: 2.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "13",
    code: "VET-013",
    name: "Cepillo para Pelo Largo Canino",
    description: "Cepillo para desenredar y cuidar el pelaje largo.",
    category: "Higiene",
    stock: 15,
    minStock: 6,
    price: 11.00,
    costPrice: 6.50,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "14",
    code: "VET-014",
    name: "Comedero Doble Acero Inoxidable",
    description: "Comedero y bebedero doble higiénico.",
    category: "Accesorios",
    stock: 22,
    minStock: 7,
    price: 19.99,
    costPrice: 12.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "15",
    code: "VET-015",
    name: "Juguete Interactivo Dispensador Comida Gato",
    description: "Juguete que dispensa comida mientras el gato juega.",
    category: "Juguetes",
    stock: 18,
    minStock: 5,
    price: 16.50,
    costPrice: 9.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "16",
    code: "VET-016",
    name: "Condroprotector Canino Articular",
    description: "Suplemento para la salud de las articulaciones en perros.",
    category: "Medicamentos",
    stock: 11,
    minStock: 4,
    price: 40.00,
    costPrice: 28.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "17",
    code: "VET-017",
    name: "Alimento Seco Cachorros Razas Pequeñas",
    description: "Fórmula específica para el crecimiento de cachorros pequeños.",
    category: "Alimento",
    stock: 28,
    minStock: 6,
    price: 38.00,
    costPrice: 25.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "18",
    code: "VET-018",
    name: "Pipeta Antiparasitaria Externa Perro Mediano",
    description: "Protección contra pulgas y garrapatas para perros medianos.",
    category: "Antiparasitarios",
    stock: 19,
    minStock: 8,
    price: 32.00,
    costPrice: 20.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "19",
    code: "VET-019",
    name: "Cortaúñas para Gatos con Tope",
    description: "Cortaúñas seguro y fácil de usar para gatos.",
    category: "Higiene",
    stock: 25,
    minStock: 5,
    price: 9.50,
    costPrice: 5.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "20",
    code: "VET-020",
    name: "Rascador para Gatos con Poste y Base",
    description: "Rascador para afilar garras y entretener al gato.",
    category: "Accesorios",
    stock: 7,
    minStock: 4,
    price: 25.00,
    costPrice: 15.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "21",
    code: "VET-021",
    name: "Collar Isabelino Plástico Perro Mediano",
    description: "Collar protector para evitar que la mascota se lama o muerda heridas.",
    category: "Accesorios",
    stock: 15,
    minStock: 7,
    price: 8.00,
    costPrice: 4.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "22",
    code: "VET-022",
    name: "Spray Repelente de Mosquitos para Perros",
    description: "Spray para proteger al perro de picaduras de mosquitos.",
    category: "Antiparasitarios",
    stock: 14,
    minStock: 5,
    price: 17.00,
    costPrice: 10.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "23",
    code: "VET-023",
    name: "Pasta Dental Enzimática Canina",
    description: "Pasta de dientes para perros que ayuda a prevenir la placa.",
    category: "Cuidado Dental",
    stock: 20,
    minStock: 6,
    price: 13.50,
    costPrice: 7.50,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "24",
    code: "VET-024",
    name: "Solución Oftálmica Lubricante Mascotas",
    description: "Gotas para lubricar y limpiar los ojos de perros y gatos.",
    category: "Cuidado Ocular/Otico",
    stock: 16,
    minStock: 4,
    price: 10.00,
    costPrice: 6.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "25",
    code: "VET-025",
    name: "Alimento Seco para Gatos Esterilizados",
    description: "Fórmula baja en calorías para gatos castrados/esterilizados.",
    category: "Alimento",
    stock: 35,
    minStock: 8,
    price: 42.00,
    costPrice: 28.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "26",
    code: "VET-026",
    name: "Juguete Cuerda Nudos para Perros",
    description: "Juguete resistente para morder y jugar a tirar.",
    category: "Juguetes",
    stock: 30,
    minStock: 7,
    price: 7.50,
    costPrice: 4.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "27",
    code: "VET-027",
    name: "Arnés Pechera Antitirones Canino",
    description: "Arnés diseñado para reducir tirones durante el paseo.",
    category: "Accesorios",
    stock: 12,
    minStock: 5,
    price: 28.00,
    costPrice: 16.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "28",
    code: "VET-028",
    name: "Spray Eliminador de Olores Mascotas",
    description: "Neutraliza y elimina olores de orina y otros fluidos.",
    category: "Higiene",
    stock: 22,
    minStock: 6,
    price: 14.00,
    costPrice: 8.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "29",
    code: "VET-029",
    name: "Probióticos para Perros y Gatos",
    description: "Suplemento para mejorar la salud digestiva.",
    category: "Vitaminas",
    stock: 10,
    minStock: 4,
    price: 20.00,
    costPrice: 12.00,
    supplier: "Laboratorio Nutrición D"
  },
  {
    id: "30",
    code: "VET-030",
    name: "Pipeta Antiparasitaria Externa Perro Pequeño",
    description: "Protección spot-on para perros pequeños.",
    category: "Antiparasitarios",
    stock: 21,
    minStock: 5,
    price: 26.00,
    costPrice: 16.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "31",
    code: "VET-031",
    name: "Alimento Seco Senior Canino",
    description: "Fórmula adaptada a las necesidades de perros mayores.",
    category: "Alimento",
    stock: 26,
    minStock: 7,
    price: 48.00,
    costPrice: 32.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "32",
    code: "VET-032",
    name: "Guante Cepillo para Cepillado Suave",
    description: "Guante con púas de goma para cepillar y masajear.",
    category: "Higiene",
    stock: 18,
    minStock: 4,
    price: 6.00,
    costPrice: 3.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "33",
    code: "VET-033",
    name: "Bebedero Automático Fuente Gatos",
    description: "Fuente de agua circulante para estimular la hidratación.",
    category: "Accesorios",
    stock: 9,
    minStock: 6,
    price: 35.00,
    costPrice: 20.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "34",
    code: "VET-034",
    name: "Juguete Peluche con Sonido Animales",
    description: "Peluche suave con sonido para entretener.",
    category: "Juguetes",
    stock: 40,
    minStock: 8,
    price: 8.99,
    costPrice: 4.50,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "35",
    code: "VET-035",
    name: "Antidiarreico Oral Perros y Gatos",
    description: "Solución para ayudar a controlar diarreas leves.",
    category: "Medicamentos",
    stock: 14,
    minStock: 5,
    price: 16.00,
    costPrice: 9.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "36",
    code: "VET-036",
    name: "Alimento Húmedo Gatitos",
    description: "Pate o trocitos en salsa para la alimentación de gatitos.",
    category: "Alimento",
    stock: 30,
    minStock: 4,
    price: 2.50,
    costPrice: 1.50,
    supplier: "Marca PetFood Y"
  },
  {
    id: "37",
    code: "VET-037",
    name: "Peine Metálico Doble Púas",
    description: "Peine con púas finas y gruesas para diferentes tipos de pelo.",
    category: "Higiene",
    stock: 20,
    minStock: 7,
    price: 10.00,
    costPrice: 5.50,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "38",
    code: "VET-038",
    name: "Cama Redonda Acolchada Mascotas",
    description: "Cama suave y cómoda para descanso.",
    category: "Accesorios",
    stock: 8,
    minStock: 5,
    price: 45.00,
    costPrice: 28.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "39",
    code: "VET-039",
    name: "Juguete Mordedor Goma Forma Hueso",
    description: "Mordedor resistente para la higiene dental canina.",
    category: "Juguetes",
    stock: 25,
    minStock: 6,
    price: 12.50,
    costPrice: 7.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "40",
    code: "VET-040",
    name: "Spray Calmante para Perros y Gatos",
    description: "Spray a base de feromonas para reducir el estrés.",
    category: "Comportamiento",
    stock: 11,
    minStock: 4,
    price: 30.00,
    costPrice: 18.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "41",
    code: "VET-041",
    name: "Alimento Seco Terapéutico Articular Canino",
    description: "Dieta para perros con problemas articulares.",
    category: "Alimento Terapéutico",
    stock: 7,
    minStock: 4,
    price: 55.00,
    costPrice: 38.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "42",
    code: "VET-042",
    name: "Kit Limpieza Dental Perros",
    description: "Incluye cepillo de dientes y pasta.",
    category: "Cuidado Dental",
    stock: 15,
    minStock: 5,
    price: 19.00,
    costPrice: 11.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "43",
    code: "VET-043",
    name: "Limpiador de Lágrimas para Perros",
    description: "Solución para limpiar las manchas de lágrimas debajo de los ojos.",
    category: "Cuidado Ocular/Otico",
    stock: 18,
    minStock: 7,
    price: 13.00,
    costPrice: 7.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "44",
    code: "VET-044",
    name: "Jaula Metálica Plegable Perro Mediano",
    description: "Jaula transportadora y de entrenamiento.",
    category: "Accesorios",
    stock: 6,
    minStock: 4,
    price: 60.00,
    costPrice: 40.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "45",
    code: "VET-045",
    name: "Rascador Poste con Plataforma Gato",
    description: "Rascador con diferentes niveles para escalar.",
    category: "Accesorios",
    stock: 10,
    minStock: 8,
    price: 50.00,
    costPrice: 30.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "46",
    code: "VET-046",
    name: "Snacks de Entrenamiento Premios Pequeños",
    description: "Premios bajos en calorías para adiestramiento.",
    category: "Alimento",
    stock: 50,
    minStock: 6,
    price: 9.00,
    costPrice: 4.00,
    supplier: "Marca PetFood Y"
  },
  {
    id: "47",
    code: "VET-047",
    name: "Champú Seco para Mascotas",
    description: "Champú en polvo para limpiar sin agua.",
    category: "Higiene",
    stock: 22,
    minStock: 5,
    price: 12.00,
    costPrice: 7.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "48",
    code: "VET-048",
    name: "Spray Antiparasitario Ambiental",
    description: "Spray para desinfestar el hogar de pulgas y garrapatas.",
    category: "Antiparasitarios",
    stock: 13,
    minStock: 4,
    price: 25.00,
    costPrice: 15.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "49",
    code: "VET-049",
    name: "Suplemento Ácidos Grasos Omega 3 y 6",
    description: "Ayuda a la salud de la piel y el pelo.",
    category: "Vitaminas",
    stock: 16,
    minStock: 7,
    price: 28.00,
    costPrice: 17.00,
    supplier: "Laboratorio Nutrición D"
  },
  {
    id: "50",
    code: "VET-050",
    name: "Juguete Dispensador de Golosinas Interactivo Canino",
    description: "Mantiene al perro entretenido dispensando premios.",
    category: "Juguetes",
    stock: 19,
    minStock: 6,
    price: 18.00,
    costPrice: 10.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "51",
    code: "VET-051",
    name: "Alimento Seco Terapéutico Control Peso Canino",
    description: "Dieta baja en calorías para perros con sobrepeso.",
    category: "Alimento Terapéutico",
    stock: 8,
    minStock: 4,
    price: 50.00,
    costPrice: 35.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "52",
    code: "VET-052",
    name: "Cepillo de Dientes Dedo para Mascotas",
    description: "Se coloca en el dedo para cepillar los dientes fácilmente.",
    category: "Cuidado Dental",
    stock: 30,
    minStock: 8,
    price: 5.00,
    costPrice: 2.50,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "53",
    code: "VET-053",
    name: "Limpiador de Ojos Solución Salina",
    description: "Solución estéril para limpiar suavemente los ojos.",
    category: "Cuidado Ocular/Otico",
    stock: 21,
    minStock: 5,
    price: 9.00,
    costPrice: 5.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "54",
    code: "VET-054",
    name: "Correa Retráctil 5 Metros Perro Mediano",
    description: "Correa extensible para paseos con más libertad.",
    category: "Accesorios",
    stock: 14,
    minStock: 6,
    price: 22.00,
    costPrice: 13.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "55",
    code: "VET-055",
    name: "Rascador Cartón con Catnip Gatos",
    description: "Rascador desechable con hierba gatera.",
    category: "Accesorios",
    stock: 25,
    minStock: 7,
    price: 7.00,
    costPrice: 3.50,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "56",
    code: "VET-056",
    name: "Tabletas Antieméticas para Perros",
    description: "Ayuda a prevenir el vómito en perros.",
    category: "Medicamentos",
    stock: 10,
    minStock: 4,
    price: 18.00,
    costPrice: 11.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "57",
    code: "VET-057",
    name: "Alimento Seco para Gatos Sensibles Digestivo",
    description: "Fórmula para gatos con estómagos sensibles.",
    category: "Alimento",
    stock: 28,
    minStock: 5,
    price: 40.00,
    costPrice: 27.00,
    supplier: "Marca PetFood Y"
  },
  {
    id: "58",
    code: "VET-058",
    name: "Toallitas Húmedas Limpiadoras Mascotas",
    description: "Toallitas para limpiar patas y cuerpo rápidamente.",
    category: "Higiene",
    stock: 35,
    minStock: 8,
    price: 9.00,
    costPrice: 5.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "59",
    code: "VET-059",
    name: "Spray Desenredante Pelo Canino",
    description: "Facilita el cepillado y ayuda a desenredar nudos.",
    category: "Higiene",
    stock: 17,
    minStock: 6,
    price: 15.00,
    costPrice: 8.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "60",
    code: "VET-060",
    name: "Juguete Pelota Interactiva con Sonido",
    description: "Pelota que emite sonidos al moverse.",
    category: "Juguetes",
    stock: 22,
    minStock: 4,
    price: 11.50,
    costPrice: 6.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "61",
    code: "VET-061",
    name: "Suplemento para Piel y Pelaje Gatos",
    description: "Ayuda a mantener un pelaje sano y brillante.",
    category: "Vitaminas",
    stock: 13,
    minStock: 5,
    price: 20.00,
    costPrice: 12.00,
    supplier: "Laboratorio Nutrición D"
  },
  {
    id: "62",
    code: "VET-062",
    name: "Pipeta Antiparasitaria Externa Perro Grande",
    description: "Protección spot-on para perros grandes.",
    category: "Antiparasitarios",
    stock: 16,
    minStock: 7,
    price: 38.00,
    costPrice: 24.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "63",
    code: "VET-063",
    name: "Alimento Seco Terapéutico Urinario Felino",
    description: "Dieta para gatos con problemas del tracto urinario.",
    category: "Alimento Terapéutico",
    stock: 9,
    minStock: 4,
    price: 48.00,
    costPrice: 33.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "64",
    code: "VET-064",
    name: "Cepillo de Púas Metálicas para Subpelo",
    description: "Ideal para eliminar el pelo muerto del subpelo.",
    category: "Higiene",
    stock: 19,
    minStock: 6,
    price: 14.00,
    costPrice: 8.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "65",
    code: "VET-065",
    name: "Comedero Elevado para Perros Grandes",
    description: "Ayuda a la digestión y reduce la tensión en el cuello.",
    category: "Accesorios",
    stock: 7,
    minStock: 4,
    price: 55.00,
    costPrice: 35.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "66",
    code: "VET-066",
    name: "Juguete Dispensador Lento de Comida",
    description: "Retrasa la ingesta de alimento y entretiene.",
    category: "Juguetes",
    stock: 15,
    minStock: 5,
    price: 20.00,
    costPrice: 12.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "67",
    code: "VET-067",
    name: "Antibiótico Oral Amplio Espectro (Receta)",
    description: "Medicamento antibiótico para diversas infecciones (Requiere receta).",
    category: "Medicamentos (Receta)",
    stock: 10,
    minStock: 8,
    price: 30.00,
    costPrice: 18.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "68",
    code: "VET-068",
    name: "Alimento Seco para Perros con Alergias Cutáneas",
    description: "Dieta hipoalergénica para perros con problemas de piel.",
    category: "Alimento Terapéutico",
    stock: 8,
    minStock: 4,
    price: 60.00,
    costPrice: 42.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "69",
    code: "VET-069",
    name: "Cepillo de Goma para Masaje y Cepillado",
    description: "Cepillo suave que masajea y recoge el pelo suelto.",
    category: "Higiene",
    stock: 25,
    minStock: 7,
    price: 9.50,
    costPrice: 5.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "70",
    code: "VET-070",
    name: "Collar Antiparasitario Gato",
    description: "Collar para el control de pulgas y garrapatas en gatos.",
    category: "Antiparasitarios",
    stock: 18,
    minStock: 5,
    price: 20.00,
    costPrice: 12.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "71",
    code: "VET-071",
    name: "Tapete Absorbente para Entrenar Cachorros",
    description: "Tapetes sanitarios para enseñar a los cachorros.",
    category: "Higiene",
    stock: 40,
    minStock: 6,
    price: 15.00,
    costPrice: 8.00,
    supplier: "Marca Arena F"
  },
  {
    id: "72",
    code: "VET-072",
    name: "Juguete Sonoro Pelota Erizo",
    description: "Pelota de goma con textura y sonido.",
    category: "Juguetes",
    stock: 30,
    minStock: 4,
    price: 7.00,
    costPrice: 3.50,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "73",
    code: "VET-073",
    name: "Suplemento para el Estrés y la Ansiedad Mascotas",
    description: "Ayuda a calmar a perros y gatos en situaciones de estrés.",
    category: "Comportamiento",
    stock: 12,
    minStock: 8,
    price: 25.00,
    costPrice: 15.00,
    supplier: "Laboratorio Nutrición D"
  },
  {
    id: "74",
    code: "VET-074",
    name: "Guantes de Látex para Exploración (Caja)",
    description: "Guantes desechables para uso veterinario.",
    category: "Insumos Médicos",
    stock: 15,
    minStock: 5,
    price: 10.00,
    costPrice: 6.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "75",
    code: "VET-075",
    name: "Venda Elástica Cohesiva",
    description: "Venda autoadhesiva para vendajes.",
    category: "Insumos Médicos",
    stock: 20,
    minStock: 7,
    price: 5.00,
    costPrice: 2.50,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "76",
    code: "VET-076",
    name: "Antiparasitario Interno Gatitos",
    description: "Suspensión oral para desparasitar gatitos.",
    category: "Medicamentos",
    stock: 14,
    minStock: 4,
    price: 15.00,
    costPrice: 9.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "77",
    code: "VET-077",
    name: "Alimento Húmedo Senior Felino",
    description: "Pate o trozos en salsa para gatos mayores.",
    category: "Alimento",
    stock: 28,
    minStock: 6,
    price: 2.80,
    costPrice: 1.80,
    supplier: "Marca PetFood Y"
  },
  {
    id: "78",
    code: "VET-078",
    name: "Cortanudos para Perros Pelo Largo",
    description: "Herramienta para eliminar nudos y enredos.",
    category: "Higiene",
    stock: 16,
    minStock: 5,
    price: 18.00,
    costPrice: 10.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "79",
    code: "VET-079",
    name: "Cama Tipo Iglú para Gatos",
    description: "Cama cerrada que proporciona seguridad y calor.",
    category: "Accesorios",
    stock: 9,
    minStock: 4,
    price: 38.00,
    costPrice: 24.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "80",
    code: "VET-080",
    name: "Juguete Ratón con Catnip para Gatos",
    description: "Clásico juguete con hierba gatera.",
    category: "Juguetes",
    stock: 35,
    minStock: 7,
    price: 4.50,
    costPrice: 2.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "81",
    code: "VET-081",
    name: "Spray Antiséptico Tópico Mascotas",
    description: "Spray para limpiar y desinfectar pequeñas heridas.",
    category: "Medicamentos",
    stock: 15,
    minStock: 5,
    price: 12.00,
    costPrice: 7.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "82",
    code: "VET-082",
    name: "Alimento Seco para Perros con Problemas Digestivos",
    description: "Dieta de fácil digestión para perros con sensibilidades gastrointestinales.",
    category: "Alimento Terapéutico",
    stock: 7,
    minStock: 4,
    price: 52.00,
    costPrice: 36.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "83",
    code: "VET-083",
    name: "Enjuague Bucal Aditivo para Agua Canino",
    description: "Se añade al agua para ayudar a reducir la placa.",
    category: "Cuidado Dental",
    stock: 18,
    minStock: 6,
    price: 16.00,
    costPrice: 9.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "84",
    code: "VET-084",
    name: "Limpiador de Oídos con Secante",
    description: "Ayuda a limpiar y secar el conducto auditivo.",
    category: "Cuidado Ocular/Otico",
    stock: 17,
    minStock: 5,
    price: 14.00,
    costPrice: 8.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "85",
    code: "VET-085",
    name: "Bo zal de Tela Ajustable",
    description: "Bo zal suave para limitar mordeduras.",
    category: "Accesorios",
    stock: 12,
    minStock: 4,
    price: 10.00,
    costPrice: 6.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "86",
    code: "VET-086",
    name: "Poste Rascador Árbol para Gatos",
    description: "Estructura multi-nivel para escalar, rascar y descansar.",
    category: "Accesorios",
    stock: 5,
    minStock: 4,
    price: 80.00,
    costPrice: 50.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "87",
    code: "VET-087",
    name: "Snacks para Control de Bolas de Pelo Gatos",
    description: "Ayudan a prevenir la formación de bolas de pelo.",
    category: "Alimento",
    stock: 30,
    minStock: 8,
    price: 11.00,
    costPrice: 6.00,
    supplier: "Marca PetFood Y"
  },
  {
    id: "88",
    code: "VET-088",
    name: "Champú para Perros Pelo Blanco",
    description: "Realza el brillo y la blancura del pelaje.",
    category: "Higiene",
    stock: 19,
    minStock: 6,
    price: 16.00,
    costPrice: 9.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "89",
    code: "VET-089",
    name: "Pipeta Antiparasitaria Externa Perro Extra Grande",
    description: "Protección spot-on para perros de gran tamaño.",
    category: "Antiparasitarios",
    stock: 15,
    minStock: 5,
    price: 42.00,
    costPrice: 28.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "90",
    code: "VET-090",
    name: "Juguete Interactivo Puzzle Canino",
    description: "Juguete que desafía al perro a encontrar golosinas.",
    category: "Juguetes",
    stock: 14,
    minStock: 4,
    price: 25.00,
    costPrice: 15.00,
    supplier: "Distribuidor Juguetes Z"
  },
  {
    id: "91",
    code: "VET-091",
    name: "Suplemento Articular Felino",
    description: "Ayuda a mantener la salud de las articulaciones en gatos.",
    category: "Vitaminas",
    stock: 11,
    minStock: 7,
    price: 22.00,
    costPrice: 13.00,
    supplier: "Laboratorio Nutrición D"
  },
  {
    id: "92",
    code: "VET-092",
    name: "Termómetro Digital Veterinario",
    description: "Termómetro rápido y preciso para mascotas.",
    category: "Insumos Médicos",
    stock: 8,
    minStock: 4,
    price: 20.00,
    costPrice: 12.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "93",
    code: "VET-093",
    name: "Vendas de Gasa Estéril (Paquete)",
    description: "Gasas para curas y vendajes.",
    category: "Insumos Médicos",
    stock: 25,
    minStock: 6,
    price: 8.00,
    costPrice: 4.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "94",
    code: "VET-094",
    name: "Antiparasitario Externo Spray Mascotas",
    description: "Spray para el tratamiento y prevención de pulgas y garrapatas.",
    category: "Antiparasitarios",
    stock: 16,
    minStock: 5,
    price: 20.00,
    costPrice: 12.00,
    supplier: "Proveedor Sanidad Animal B"
  },
  {
    id: "95",
    code: "VET-095",
    name: "Alimento Seco Terapéutico Hepático Canino",
    description: "Dieta de apoyo para perros con problemas hepáticos.",
    category: "Alimento Terapéutico",
    stock: 6,
    minStock: 4,
    price: 58.00,
    costPrice: 40.00,
    supplier: "Marca PetFood X"
  },
  {
    id: "96",
    code: "VET-096",
    name: "Crema Dental Sabor a Carne Canina",
    description: "Pasta de dientes con sabor agradable para perros.",
    category: "Cuidado Dental",
    stock: 20,
    minStock: 7,
    price: 10.00,
    costPrice: 6.00,
    supplier: "Productos Cuidado Mascota C"
  },
  {
    id: "97",
    code: "VET-097",
    name: "Gotas Óticas Antibacterianas (Receta)",
    description: "Tratamiento para infecciones de oído (Requiere receta).",
    category: "Medicamentos (Receta)",
    stock: 10,
    minStock: 8,
    price: 25.00,
    costPrice: 15.00,
    supplier: "Laboratorio Veterinario A"
  },
  {
    id: "98",
    code: "VET-098",
    name: "Transportín de Tela Plegable",
    description: "Transportín ligero y fácil de guardar.",
    category: "Accesorios",
    stock: 9,
    minStock: 4,
    price: 35.00,
    costPrice: 20.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "99",
    code: "VET-099",
    name: "Rascador Vertical con Juguete Colgante Gato",
    description: "Poste rascador con juguete para mayor diversión.",
    category: "Accesorios",
    stock: 12,
    minStock: 6,
    price: 20.00,
    costPrice: 12.00,
    supplier: "Distribuidor Equipamiento E"
  },
  {
    id: "100",
    code: "VET-100",
    name: "Juguete Pelota para Dispensar Premios Gatos",
    description: "Estimula el juego y dispensa pequeñas golosinas.",
    category: "Juguetes",
    stock: 18,
    minStock: 5,
    price: 15.00,
    costPrice: 8.00,
    supplier: "Distribuidor Juguetes Z"
  }
]
export const inventoryMovements = [
  // Example Movement (similar to the one provided)
  {
    id: 1,
    type: "entrada", // Type of movement: 'entrada' (entry) or 'salida' (exit)
    description: "Compra inicial de stock", // Description of the movement
    date: "2025-01-10T08:00:00", // Date and time of the movement (ISO 8601 format)
    quantity: 50, // Quantity of products involved in the movement
    products: ["Antibiótico AmoxiVet 500mg"], // Array of product names involved
    reference: "COMP-2025-001", // Reference code for the movement (e.g., invoice, order number)
  },
  {
    id: 2,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-01-15T10:30:00",
    quantity: 100,
    products: ["Vacuna Canina DHPPiL"],
    reference: "COMP-2025-002",
  },
  {
    id: 3,
    type: "salida",
    description: "Venta a cliente Sr. Pérez",
    date: "2025-01-16T11:05:00",
    quantity: 2,
    products: ["Antibiótico AmoxiVet 500mg"],
    reference: "VENT-2025-001",
  },
  {
    id: 4,
    type: "salida",
    description: "Venta a cliente Sra. Gómez",
    date: "2025-01-17T14:20:00",
    quantity: 5,
    products: ["Vacuna Canina DHPPiL"],
    reference: "VENT-2025-002",
  },
  {
    id: 5,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-01-20T09:15:00",
    quantity: 30,
    products: ["Desparasitante Prazitel Perros"],
    reference: "COMP-2025-003",
  },
  {
    id: 6,
    type: "salida",
    description: "Uso interno para tratamiento",
    date: "2025-01-21T16:00:00",
    quantity: 1,
    products: ["Antibiótico AmoxiVet 500mg"],
    reference: "USO-2025-001",
  },
  {
    id: 7,
    type: "salida",
    description: "Venta a cliente Clínica Animalia",
    date: "2025-01-22T10:00:00",
    quantity: 10,
    products: ["Desparasitante Prazitel Perros"],
    reference: "VENT-2025-003",
  },
  {
    id: 8,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-01-25T11:45:00",
    quantity: 25,
    products: ["Shampoo Medicado Clorhexidina"],
    reference: "COMP-2025-004",
  },
  {
    id: 9,
    type: "salida",
    description: "Venta a cliente Sr. Ramírez",
    date: "2025-01-26T15:30:00",
    quantity: 1,
    products: ["Shampoo Medicado Clorhexidina"],
    reference: "VENT-2025-004",
  },
  {
    id: 10,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-02-01T08:30:00",
    quantity: 40,
    products: ["Alimento Royal Canin Vet Diet Renal Gato"],
    reference: "COMP-2025-005",
  },
  // --- Adding more movements ---
  {
    id: 11,
    type: "salida",
    description: "Venta a cliente Sra. López",
    date: "2025-02-02T12:10:00",
    quantity: 3,
    products: ["Alimento Royal Canin Vet Diet Renal Gato"],
    reference: "VENT-2025-005",
  },
  {
    id: 12,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-02-05T09:00:00",
    quantity: 60,
    products: ["Antibiótico Enrofloxacina 50mg"],
    reference: "COMP-2025-006",
  },
  {
    id: 13,
    type: "salida",
    description: "Uso interno para hospitalización",
    date: "2025-02-06T17:00:00",
    quantity: 4,
    products: ["Antibiótico Enrofloxacina 50mg"],
    reference: "USO-2025-002",
  },
  {
    id: 14,
    type: "salida",
    description: "Venta a cliente Sr. Castillo",
    date: "2025-02-07T11:55:00",
    quantity: 1,
    products: ["Vacuna Canina DHPPiL"],
    reference: "VENT-2025-006",
  },
  {
    id: 15,
    type: "entrada",
    description: "Devolución de cliente Sra. Gómez",
    date: "2025-02-08T10:15:00",
    quantity: 1,
    products: ["Vacuna Canina DHPPiL"],
    reference: "DEV-2025-001",
  },
  {
    id: 16,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-02-10T14:00:00",
    quantity: 20,
    products: ["Analgésico Meloxicam Gotas"],
    reference: "COMP-2025-007",
  },
  {
    id: 17,
    type: "salida",
    description: "Venta a cliente Sra. Díaz",
    date: "2025-02-11T09:45:00",
    quantity: 1,
    products: ["Analgésico Meloxicam Gotas"],
    reference: "VENT-2025-007",
  },
  {
    id: 18,
    type: "salida",
    description: "Ajuste por caducidad",
    date: "2025-02-12T18:00:00",
    quantity: 2,
    products: ["Antibiótico AmoxiVet 500mg"],
    reference: "AJST-2025-001",
  },
  {
    id: 19,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-02-15T11:00:00",
    quantity: 50,
    products: ["Suero Fisiológico 500ml"],
    reference: "COMP-2025-008",
  },
  {
    id: 20,
    type: "salida",
    description: "Uso en cirugía",
    date: "2025-02-16T13:30:00",
    quantity: 3,
    products: ["Suero Fisiológico 500ml"],
    reference: "USO-2025-003",
  },
  {
    id: 21,
    type: "salida",
    description: "Venta a cliente Sr. Vargas",
    date: "2025-02-17T10:20:00",
    quantity: 2,
    products: ["Desparasitante Prazitel Perros"],
    reference: "VENT-2025-008",
  },
  {
    id: 22,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-02-20T09:30:00",
    quantity: 15,
    products: ["Protector Hepático Silimarina"],
    reference: "COMP-2025-009",
  },
  {
    id: 23,
    type: "salida",
    description: "Venta a cliente Sra. Méndez",
    date: "2025-02-21T16:15:00",
    quantity: 1,
    products: ["Protector Hepático Silimarina"],
    reference: "VENT-2025-009",
  },
  {
    id: 24,
    type: "salida",
    description: "Venta a cliente Sr. Silva",
    date: "2025-02-22T11:00:00",
    quantity: 1,
    products: ["Shampoo Medicado Clorhexidina"],
    reference: "VENT-2025-010",
  },
  {
    id: 25,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-02-25T10:45:00",
    quantity: 80,
    products: ["Vacuna Felina Triple"],
    reference: "COMP-2025-010",
  },
  {
    id: 26,
    type: "salida",
    description: "Venta a cliente Sra. Ríos",
    date: "2025-02-26T14:00:00",
    quantity: 3,
    products: ["Vacuna Felina Triple"],
    reference: "VENT-2025-011",
  },
  {
    id: 27,
    type: "salida",
    description: "Venta a cliente Sr. Núñez",
    date: "2025-02-27T09:50:00",
    quantity: 2,
    products: ["Alimento Royal Canin Vet Diet Renal Gato"],
    reference: "VENT-2025-012",
  },
  {
    id: 28,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-03-01T08:15:00",
    quantity: 25,
    products: ["Antiinflamatorio Carprofeno 50mg"],
    reference: "COMP-2025-011",
  },
  {
    id: 29,
    type: "salida",
    description: "Venta a cliente Sra. Mora",
    date: "2025-03-02T11:30:00",
    quantity: 1,
    products: ["Antiinflamatorio Carprofeno 50mg"],
    reference: "VENT-2025-013",
  },
  {
    id: 30,
    type: "salida",
    description: "Uso interno post-operatorio",
    date: "2025-03-03T15:00:00",
    quantity: 2,
    products: ["Antibiótico Enrofloxacina 50mg"],
    reference: "USO-2025-004",
  },
  // ... (Adding 95 more entries to reach ~125)
  {
    id: 31,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-03-05T10:00:00",
    quantity: 40,
    products: ["Pipeta Antipulgas Fipronil Perro Mediano"],
    reference: "COMP-2025-012",
  },
  {
    id: 32,
    type: "salida",
    description: "Venta a cliente Sr. Torres",
    date: "2025-03-06T14:25:00",
    quantity: 2,
    products: ["Pipeta Antipulgas Fipronil Perro Mediano"],
    reference: "VENT-2025-014",
  },
  {
    id: 33,
    type: "salida",
    description: "Venta a cliente Sra. Vega",
    date: "2025-03-07T09:10:00",
    quantity: 1,
    products: ["Analgésico Meloxicam Gotas"],
    reference: "VENT-2025-015",
  },
  {
    id: 34,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-03-10T11:15:00",
    quantity: 10,
    products: ["Alimento Hill's Prescription Diet k/d Gato"],
    reference: "COMP-2025-013",
  },
  {
    id: 35,
    type: "salida",
    description: "Venta a cliente Sr. Romero",
    date: "2025-03-11T16:40:00",
    quantity: 1,
    products: ["Alimento Hill's Prescription Diet k/d Gato"],
    reference: "VENT-2025-016",
  },
  {
    id: 36,
    type: "salida",
    description: "Uso en consulta",
    date: "2025-03-12T10:50:00",
    quantity: 5,
    products: ["Suero Fisiológico 500ml"],
    reference: "USO-2025-005",
  },
  {
    id: 37,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-03-15T08:45:00",
    quantity: 30,
    products: ["Gotas Óticas Antibióticas/Antiinflamatorias"],
    reference: "COMP-2025-014",
  },
  {
    id: 38,
    type: "salida",
    description: "Venta a cliente Sra. Peña",
    date: "2025-03-16T12:00:00",
    quantity: 1,
    products: ["Gotas Óticas Antibióticas/Antiinflamatorias"],
    reference: "VENT-2025-017",
  },
  {
    id: 39,
    type: "salida",
    description: "Venta a cliente Sr. Blanco",
    date: "2025-03-17T15:15:00",
    quantity: 1,
    products: ["Protector Hepático Silimarina"],
    reference: "VENT-2025-018",
  },
  {
    id: 40,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-03-20T09:55:00",
    quantity: 70,
    products: ["Vacuna Canina Rabia"],
    reference: "COMP-2025-015",
  },
   {
    id: 41,
    type: "salida",
    description: "Campaña de vacunación",
    date: "2025-03-21T10:00:00",
    quantity: 15,
    products: ["Vacuna Canina Rabia"],
    reference: "CAMP-2025-001",
  },
  {
    id: 42,
    type: "salida",
    description: "Venta a cliente Sra. Soto",
    date: "2025-03-22T11:20:00",
    quantity: 1,
    products: ["Vacuna Canina Rabia"],
    reference: "VENT-2025-019",
  },
  {
    id: 43,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-03-25T14:10:00",
    quantity: 20,
    products: ["Cicatrizante en Spray Plata"],
    reference: "COMP-2025-016",
  },
  {
    id: 44,
    type: "salida",
    description: "Uso en curación",
    date: "2025-03-26T16:05:00",
    quantity: 1,
    products: ["Cicatrizante en Spray Plata"],
    reference: "USO-2025-006",
  },
  {
    id: 45,
    type: "salida",
    description: "Venta a cliente Sr. Herrera",
    date: "2025-03-27T09:35:00",
    quantity: 1,
    products: ["Antiinflamatorio Carprofeno 50mg"],
    reference: "VENT-2025-020",
  },
  {
    id: 46,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2025-03-30T10:30:00",
    quantity: 50,
    products: ["Antibiótico Doxiciclina 100mg"],
    reference: "COMP-2025-017",
  },
  {
    id: 47,
    type: "salida",
    description: "Venta a cliente Clínica San Roque",
    date: "2025-04-01T11:00:00",
    quantity: 10,
    products: ["Antibiótico Doxiciclina 100mg"],
    reference: "VENT-2025-021",
  },
  {
    id: 48,
    type: "salida",
    description: "Venta a cliente Sra. Luna",
    date: "2025-04-02T15:45:00",
    quantity: 1,
    products: ["Pipeta Antipulgas Fipronil Perro Mediano"],
    reference: "VENT-2025-022",
  },
  {
    id: 49,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2025-04-05T09:20:00",
    quantity: 15,
    products: ["Suplemento Articular Condroitina/Glucosamina"],
    reference: "COMP-2025-018",
  },
  {
    id: 50,
    type: "salida",
    description: "Venta a cliente Sr. Medina",
    date: "2025-04-06T12:15:00",
    quantity: 1,
    products: ["Suplemento Articular Condroitina/Glucosamina"],
    reference: "VENT-2025-023",
  },
  // --- Continue adding entries ---
  // ... (Generating more entries up to ~125)
  { id: 51, type: "salida", description: "Venta a cliente Sra. Campos", date: "2025-04-07T10:05:00", quantity: 1, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "VENT-2024-024" },
  { id: 52, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-04-10T11:50:00", quantity: 35, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "COMP-2024-019" },
  { id: 53, type: "salida", description: "Venta a cliente Sr. Osorio", date: "2025-04-11T14:30:00", quantity: 3, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "VENT-2024-025" },
  { id: 54, type: "salida", description: "Ajuste por rotura", date: "2025-04-12T17:45:00", quantity: 1, products: ["Suero Fisiológico 500ml"], reference: "AJST-2024-002" },
  { id: 55, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-04-15T09:00:00", quantity: 25, products: ["Antibiótico Cefalexina 500mg"], reference: "COMP-2024-020" },
  { id: 56, type: "salida", description: "Venta a cliente Sra. Paredes", date: "2025-04-16T10:40:00", quantity: 1, products: ["Antibiótico Cefalexina 500mg"], reference: "VENT-2024-026" },
  { id: 57, type: "salida", description: "Uso interno", date: "2025-04-17T16:20:00", quantity: 1, products: ["Gotas Óticas Antibióticas/Antiinflamatorias"], reference: "USO-2024-007" },
  { id: 58, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-04-20T13:10:00", quantity: 10, products: ["Alimento Royal Canin Vet Diet Urinary SO Perro"], reference: "COMP-2024-021" },
  { id: 59, type: "salida", description: "Venta a cliente Sr. Franco", date: "2025-04-21T11:00:00", quantity: 2, products: ["Alimento Royal Canin Vet Diet Urinary SO Perro"], reference: "VENT-2024-027" },
  { id: 60, type: "salida", description: "Venta a cliente Sra. Pinto", date: "2025-04-22T15:00:00", quantity: 1, products: ["Vacuna Canina Rabia"], reference: "VENT-2024-028" },
  { id: 61, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-04-25T08:30:00", quantity: 60, products: ["Desparasitante Interno Febendazol Suspensión"], reference: "COMP-2024-022" },
  { id: 62, type: "salida", description: "Venta a criadero CanFeliz", date: "2025-04-26T10:15:00", quantity: 5, products: ["Desparasitante Interno Febendazol Suspensión"], reference: "VENT-2024-029" },
  { id: 63, type: "salida", description: "Venta a cliente Sr. Solis", date: "2025-04-27T14:55:00", quantity: 1, products: ["Cicatrizante en Spray Plata"], reference: "VENT-2024-030" },
  { id: 64, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-04-30T11:25:00", quantity: 20, products: ["Vitaminas Complejo B Inyectable"], reference: "COMP-2024-023" },
  { id: 65, type: "salida", description: "Uso en tratamiento anemia", date: "2025-05-01T16:30:00", quantity: 2, products: ["Vitaminas Complejo B Inyectable"], reference: "USO-2024-008" },
  { id: 66, type: "salida", description: "Venta a cliente Sra. Bravo", date: "2025-05-02T09:40:00", quantity: 1, products: ["Antibiótico Doxiciclina 100mg"], reference: "VENT-2024-031" },
  { id: 67, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-05-05T10:00:00", quantity: 30, products: ["Shampoo Antipulgas Permetrina"], reference: "COMP-2024-024" },
  { id: 68, type: "salida", description: "Venta a cliente Sr. Reyes", date: "2025-05-06T13:05:00", quantity: 1, products: ["Shampoo Antipulgas Permetrina"], reference: "VENT-2024-032" },
  { id: 69, type: "salida", description: "Venta a cliente Sra. Gil", date: "2025-05-07T15:20:00", quantity: 1, products: ["Suplemento Articular Condroitina/Glucosamina"], reference: "VENT-2024-033" },
  { id: 70, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-05-10T08:50:00", quantity: 45, products: ["Antibiótico AmoxiVet 500mg"], reference: "COMP-2024-025" },
  { id: 71, type: "salida", description: "Venta a cliente Sr. León", date: "2025-05-11T11:10:00", quantity: 3, products: ["Antibiótico AmoxiVet 500mg"], reference: "VENT-2024-034" },
  { id: 72, type: "salida", description: "Venta a cliente Sra. Cruz", date: "2025-05-12T14:40:00", quantity: 2, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "VENT-2024-035" },
  { id: 73, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-05-15T09:30:00", quantity: 90, products: ["Vacuna Canina DHPPiL"], reference: "COMP-2024-026" },
  { id: 74, type: "salida", description: "Venta a cliente Sr. Marin", date: "2025-05-16T10:25:00", quantity: 4, products: ["Vacuna Canina DHPPiL"], reference: "VENT-2024-036" },
  { id: 75, type: "salida", description: "Venta a cliente Sra. Ortiz", date: "2025-05-17T16:00:00", quantity: 1, products: ["Antibiótico Cefalexina 500mg"], reference: "VENT-2024-037" },
  { id: 76, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-05-20T11:00:00", quantity: 20, products: ["Desparasitante Prazitel Perros"], reference: "COMP-2024-027" },
  { id: 77, type: "salida", description: "Venta a cliente Sr. Castro", date: "2025-05-21T13:45:00", quantity: 2, products: ["Desparasitante Prazitel Perros"], reference: "VENT-2024-038" },
  { id: 78, type: "salida", description: "Uso interno", date: "2025-05-22T17:10:00", quantity: 1, products: ["Alimento Royal Canin Vet Diet Urinary SO Perro"], reference: "USO-2024-009" },
  { id: 79, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-05-25T09:15:00", quantity: 30, products: ["Shampoo Medicado Clorhexidina"], reference: "COMP-2024-028" },
  { id: 80, type: "salida", description: "Venta a cliente Sra. Rubio", date: "2025-05-26T10:50:00", quantity: 1, products: ["Shampoo Medicado Clorhexidina"], reference: "VENT-2024-039" },
  { id: 81, type: "salida", description: "Venta a cliente Sr. Navarro", date: "2025-05-27T14:00:00", quantity: 3, products: ["Desparasitante Interno Febendazol Suspensión"], reference: "VENT-2024-040" },
  { id: 82, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-05-30T10:40:00", quantity: 35, products: ["Alimento Royal Canin Vet Diet Renal Gato"], reference: "COMP-2024-029" },
  { id: 83, type: "salida", description: "Venta a cliente Sra. Iglesias", date: "2025-06-01T11:55:00", quantity: 2, products: ["Alimento Royal Canin Vet Diet Renal Gato"], reference: "VENT-2024-041" },
  { id: 84, type: "salida", description: "Uso en hospitalización", date: "2025-06-02T16:45:00", quantity: 1, products: ["Vitaminas Complejo B Inyectable"], reference: "USO-2024-010" },
  { id: 85, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-06-05T08:20:00", quantity: 55, products: ["Antibiótico Enrofloxacina 50mg"], reference: "COMP-2024-030" },
  { id: 86, type: "salida", description: "Venta a cliente Sr. Cano", date: "2025-06-06T10:30:00", quantity: 2, products: ["Antibiótico Enrofloxacina 50mg"], reference: "VENT-2024-042" },
  { id: 87, type: "salida", description: "Venta a cliente Sra. Aguilar", date: "2025-06-07T13:15:00", quantity: 1, products: ["Shampoo Antipulgas Permetrina"], reference: "VENT-2024-043" },
  { id: 88, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-06-10T09:05:00", quantity: 18, products: ["Analgésico Meloxicam Gotas"], reference: "COMP-2024-031" },
  { id: 89, type: "salida", description: "Venta a cliente Sr. Parra", date: "2025-06-11T12:00:00", quantity: 1, products: ["Analgésico Meloxicam Gotas"], reference: "VENT-2024-044" },
  { id: 90, type: "salida", description: "Ajuste por caducidad", date: "2025-06-12T18:10:00", quantity: 1, products: ["Vacuna Felina Triple"], reference: "AJST-2024-003" },
  { id: 91, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-06-15T11:35:00", quantity: 40, products: ["Suero Fisiológico 500ml"], reference: "COMP-2024-032" },
  { id: 92, type: "salida", description: "Uso en cirugía", date: "2025-06-16T14:00:00", quantity: 2, products: ["Suero Fisiológico 500ml"], reference: "USO-2024-011" },
  { id: 93, type: "salida", description: "Venta a cliente Sra. Molina", date: "2025-06-17T09:50:00", quantity: 1, products: ["Antibiótico AmoxiVet 500mg"], reference: "VENT-2024-045" },
  { id: 94, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-06-20T10:10:00", quantity: 12, products: ["Protector Hepático Silimarina"], reference: "COMP-2024-033" },
  { id: 95, type: "salida", description: "Venta a cliente Sr. Delgado", date: "2025-06-21T15:05:00", quantity: 1, products: ["Protector Hepático Silimarina"], reference: "VENT-2024-046" },
  { id: 96, type: "salida", description: "Venta a cliente Sra. Santana", date: "2025-06-22T11:40:00", quantity: 2, products: ["Vacuna Canina DHPPiL"], reference: "VENT-2024-047" },
  { id: 97, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-06-25T08:55:00", quantity: 75, products: ["Vacuna Felina Triple"], reference: "COMP-2024-034" },
  { id: 98, type: "salida", description: "Venta a cliente Sr. Vidal", date: "2025-06-26T10:00:00", quantity: 2, products: ["Vacuna Felina Triple"], reference: "VENT-2024-048" },
  { id: 99, type: "salida", description: "Venta a cliente Sra. Rojas", date: "2025-06-27T14:20:00", quantity: 1, products: ["Desparasitante Prazitel Perros"], reference: "VENT-2024-049" },
  { id: 100, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-06-30T09:25:00", quantity: 22, products: ["Antiinflamatorio Carprofeno 50mg"], reference: "COMP-2024-035" },
  { id: 101, type: "salida", description: "Venta a cliente Sr. Ortega", date: "2025-07-01T11:15:00", quantity: 1, products: ["Antiinflamatorio Carprofeno 50mg"], reference: "VENT-2024-050" },
  { id: 102, type: "salida", description: "Uso interno", date: "2025-07-02T16:50:00", quantity: 1, products: ["Antibiótico Enrofloxacina 50mg"], reference: "USO-2024-012" },
  { id: 103, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-07-05T10:35:00", quantity: 38, products: ["Pipeta Antipulgas Fipronil Perro Mediano"], reference: "COMP-2024-036" },
  { id: 104, type: "salida", description: "Venta a cliente Sra. Serrano", date: "2025-07-06T13:30:00", quantity: 2, products: ["Pipeta Antipulgas Fipronil Perro Mediano"], reference: "VENT-2024-051" },
  { id: 105, type: "salida", description: "Venta a cliente Sr. Duran", date: "2025-07-07T09:00:00", quantity: 1, products: ["Analgésico Meloxicam Gotas"], reference: "VENT-2024-052" },
  { id: 106, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-07-10T11:05:00", quantity: 8, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "COMP-2024-037" },
  { id: 107, type: "salida", description: "Venta a cliente Sra. Flores", date: "2025-07-11T15:55:00", quantity: 1, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "VENT-2024-053" },
  { id: 108, type: "salida", description: "Uso en consulta", date: "2025-07-12T10:10:00", quantity: 3, products: ["Suero Fisiológico 500ml"], reference: "USO-2024-013" },
  { id: 109, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-07-15T08:40:00", quantity: 28, products: ["Gotas Óticas Antibióticas/Antiinflamatorias"], reference: "COMP-2024-038" },
  { id: 110, type: "salida", description: "Venta a cliente Sr. Acosta", date: "2025-07-16T12:25:00", quantity: 1, products: ["Gotas Óticas Antibióticas/Antiinflamatorias"], reference: "VENT-2024-054" },
  { id: 111, type: "salida", description: "Venta a cliente Sra. Benitez", date: "2025-07-17T14:50:00", quantity: 1, products: ["Protector Hepático Silimarina"], reference: "VENT-2024-055" },
  { id: 112, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-07-20T09:45:00", quantity: 65, products: ["Vacuna Canina Rabia"], reference: "COMP-2024-039" },
  { id: 113, type: "salida", description: "Campaña de vacunación", date: "2025-07-21T10:15:00", quantity: 12, products: ["Vacuna Canina Rabia"], reference: "CAMP-2024-002" },
  { id: 114, type: "salida", description: "Venta a cliente Sr. Cabrera", date: "2025-07-22T11:30:00", quantity: 1, products: ["Vacuna Canina Rabia"], reference: "VENT-2024-056" },
  { id: 115, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-07-25T13:50:00", quantity: 18, products: ["Cicatrizante en Spray Plata"], reference: "COMP-2024-040" },
  { id: 116, type: "salida", description: "Uso en curación", date: "2025-07-26T16:10:00", quantity: 1, products: ["Cicatrizante en Spray Plata"], reference: "USO-2024-014" },
  { id: 117, type: "salida", description: "Venta a cliente Sra. Dominguez", date: "2025-07-27T09:20:00", quantity: 1, products: ["Antiinflamatorio Carprofeno 50mg"], reference: "VENT-2024-057" },
  { id: 118, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-07-30T10:05:00", quantity: 45, products: ["Antibiótico Doxiciclina 100mg"], reference: "COMP-2024-041" },
  { id: 119, type: "salida", description: "Venta a cliente Clínica VetSur", date: "2025-08-01T11:20:00", quantity: 8, products: ["Antibiótico Doxiciclina 100mg"], reference: "VENT-2024-058" },
  { id: 120, type: "salida", description: "Venta a cliente Sr. Espinoza", date: "2025-08-02T15:35:00", quantity: 1, products: ["Pipeta Antipulgas Fipronil Perro Mediano"], reference: "VENT-2024-059" },
  { id: 121, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2025-08-05T09:10:00", quantity: 14, products: ["Suplemento Articular Condroitina/Glucosamina"], reference: "COMP-2024-042" },
  { id: 122, type: "salida", description: "Venta a cliente Sra. Fernandez", date: "2025-08-06T12:45:00", quantity: 1, products: ["Suplemento Articular Condroitina/Glucosamina"], reference: "VENT-2024-060" },
  { id: 123, type: "salida", description: "Venta a cliente Sr. Gallardo", date: "2025-08-07T10:20:00", quantity: 1, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "VENT-2024-061" },
  { id: 124, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2025-08-10T11:40:00", quantity: 32, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "COMP-2024-043" },
  { id: 125, type: "salida", description: "Venta a cliente Sra. Herrera", date: "2025-08-11T14:05:00", quantity: 2, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "VENT-2024-062" },
];

