export const products_json = [
    {
      "id": 1,
      "nombre": "Antibiótico Inyectable VET-A",
      "categoria": "Medicamentos",
      "stock": 75,
      "precio": 22.50,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 2,
      "nombre": "Pienso Cachorro Razas Pequeñas 3kg",
      "categoria": "Alimentos",
      "stock": 150,
      "precio": 35.99,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 3,
      "nombre": "Booster Inmune Oral Perro",
      "categoria": "Suplementos",
      "stock": 90,
      "precio": 48.10,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 4,
      "nombre": "Venda Crepé 10cm",
      "categoria": "Material Quirúrgico",
      "stock": 220,
      "precio": 4.80,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 5,
      "nombre": "Champú Antiparasitario Gato",
      "categoria": "Higiene",
      "stock": 45,
      "precio": 16.50,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 6,
      "nombre": "Pipeta Garrapatas Perro XL",
      "categoria": "Antiparasitarios",
      "stock": 115,
      "precio": 12.75,
      "img": "",
      "provedor": "ParasitVet Solutions"
    },
    {
      "id": 7,
      "nombre": "Vacuna Leptospirosis Canina",
      "categoria": "Vacunas",
      "stock": 60,
      "precio": 38.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 8,
      "nombre": "Kit Sutura Estéril",
      "categoria": "Material Quirúrgico",
      "stock": 30,
      "precio": 85.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 9,
      "nombre": "Test Filaria Canina Rápido",
      "categoria": "Diagnóstico",
      "stock": 25,
      "precio": 95.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 10,
      "nombre": "Guantes Nitrilo Talla L (Caja 100)",
      "categoria": "Material Quirúrgico",
      "stock": 18,
      "precio": 28.00,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 11,
      "nombre": "Pienso Gato Senior Control Peso",
      "categoria": "Alimentos",
      "stock": 105,
      "precio": 42.30,
      "img": "",
      "provedor": "Felinos Diet"
    },
    {
      "id": 12,
      "nombre": "Collar Cono Suave Gato",
      "categoria": "Accesorios",
      "stock": 55,
      "precio": 10.20,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 13,
      "nombre": "Crema Antifúngica Tópica",
      "categoria": "Medicamentos",
      "stock": 70,
      "precio": 19.90,
      "img": "",
      "provedor": "Dermavet Pharma"
    },
    {
      "id": 14,
      "nombre": "Limpiador Ocular Suave",
      "categoria": "Higiene",
      "stock": 85,
      "precio": 10.50,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 15,
      "nombre": "Pastillas Desparasitantes Internas (Pack 4)",
      "categoria": "Antiparasitarios",
      "stock": 130,
      "precio": 8.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 16,
      "nombre": "Vacuna Triple Felina",
      "categoria": "Vacunas",
      "stock": 50,
      "precio": 32.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 17,
      "nombre": "Complejo Vitamínico B Inyectable",
      "categoria": "Suplementos",
      "stock": 40,
      "precio": 29.75,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 18,
      "nombre": "Tiras Reactivas Glucosa",
      "categoria": "Diagnóstico",
      "stock": 35,
      "precio": 55.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 19,
      "nombre": "Endoscopio Flexible Veterinario",
      "categoria": "Equipamiento Médico",
      "stock": 1,
      "precio": 8500.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 20,
      "nombre": "Sondas Nasogástricas (Pack)",
      "categoria": "Material Quirúrgico",
      "stock": 20,
      "precio": 45.00,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 21,
      "nombre": "Jaula Hospitalización Pequeña",
      "categoria": "Equipamiento Médico",
      "stock": 3,
      "precio": 700.00,
      "img": "",
      "provedor": "Mobiliario Clínico Vet"
    },
    {
      "id": 22,
      "nombre": "Analgésico Oral Perro/Gato",
      "categoria": "Medicamentos",
      "stock": 95,
      "precio": 15.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 23,
      "nombre": "Pienso Dieta Renal Perro 2kg",
      "categoria": "Alimentos",
      "stock": 78,
      "precio": 52.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 24,
      "nombre": "Cepillo Deslanador",
      "categoria": "Accesorios",
      "stock": 60,
      "precio": 19.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 25,
      "nombre": "Gasas Estériles 10x10 (Pack)",
      "categoria": "Material Quirúrgico",
      "stock": 180,
      "precio": 10.00,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 26,
      "nombre": "Toallitas Limpieza Ojos",
      "categoria": "Higiene",
      "stock": 120,
      "precio": 7.50,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 27,
      "nombre": "Spray Repelente Insectos",
      "categoria": "Antiparasitarios",
      "stock": 50,
      "precio": 11.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 28,
      "nombre": "Vacuna Moquillo Canino",
      "categoria": "Vacunas",
      "stock": 55,
      "precio": 36.50,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 29,
      "nombre": "Probiótico Digestivo Perro",
      "categoria": "Suplementos",
      "stock": 80,
      "precio": 25.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 30,
      "nombre": "Microscopio Binocular Clínico",
      "categoria": "Equipamiento Médico",
      "stock": 2,
      "precio": 1200.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 31,
      "nombre": "Test FIV/FeLV Gato Rápido",
      "categoria": "Diagnóstico",
      "stock": 28,
      "precio": 88.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 32,
      "nombre": "Agujas Hipodérmicas 21G (Caja 100)",
      "categoria": "Material Quirúrgico",
      "stock": 15,
      "precio": 18.00,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 33,
      "nombre": "Pienso Ave Ornamentales",
      "categoria": "Alimentos",
      "stock": 200,
      "precio": 15.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 34,
      "nombre": "Comedero Acero Inoxidable Grande",
      "categoria": "Accesorios",
      "stock": 40,
      "precio": 14.50,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 35,
      "nombre": "Antiinflamatorio No Esteroideo VET",
      "categoria": "Medicamentos",
      "stock": 65,
      "precio": 30.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 36,
      "nombre": "Spray Bucal Antiséptico Perro/Gato",
      "categoria": "Higiene",
      "stock": 50,
      "precio": 13.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 37,
      "nombre": "Pipeta Mosquitos Caballo",
      "categoria": "Antiparasitarios",
      "stock": 10,
      "precio": 25.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 38,
      "nombre": "Vacuna Parvovirus Canina",
      "categoria": "Vacunas",
      "stock": 70,
      "precio": 34.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 39,
      "nombre": "Ácidos Grasos Omega 3/6 Suplemento",
      "categoria": "Suplementos",
      "stock": 88,
      "precio": 33.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 40,
      "nombre": "Ecógrafo Veterinario Portátil",
      "categoria": "Equipamiento Médico",
      "stock": 1,
      "precio": 9800.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 41,
      "nombre": "Lector Microchips Universal",
      "categoria": "Diagnóstico",
      "stock": 4,
      "precio": 350.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 42,
      "nombre": "Hojas Bisturí #10 (Caja 10)",
      "categoria": "Material Quirúrgico",
      "stock": 45,
      "precio": 9.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 43,
      "nombre": "Pienso Conejo Adulto",
      "categoria": "Alimentos",
      "stock": 160,
      "precio": 18.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 44,
      "nombre": "Correa Adiestramiento Larga",
      "categoria": "Accesorios",
      "stock": 35,
      "precio": 21.50,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 45,
      "nombre": "Sedante Leve Oral",
      "categoria": "Medicamentos",
      "stock": 55,
      "precio": 28.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 46,
      "nombre": "Champú Piel Sensible",
      "categoria": "Higiene",
      "stock": 40,
      "precio": 15.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 47,
      "nombre": "Inyectable Desparasitante Interno",
      "categoria": "Antiparasitarios",
      "stock": 30,
      "precio": 40.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 48,
      "nombre": "Vacuna Bordetella Canina",
      "categoria": "Vacunas",
      "stock": 65,
      "precio": 29.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 49,
      "nombre": "Electrolitos Orales Solución",
      "categoria": "Suplementos",
      "stock": 100,
      "precio": 17.50,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 50,
      "nombre": "Máquina Anestesia Inhalatoria",
      "categoria": "Equipamiento Médico",
      "stock": 1,
      "precio": 7500.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 51,
      "nombre": "Set Cirugía Básica",
      "categoria": "Material Quirúrgico",
      "stock": 5,
      "precio": 350.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 52,
      "nombre": "Pienso Dieta Urinaria Gato",
      "categoria": "Alimentos",
      "stock": 85,
      "precio": 49.50,
      "img": "",
      "provedor": "Felinos Diet"
    },
    {
      "id": 53,
      "nombre": "Cama Ortopédica Grande",
      "categoria": "Accesorios",
      "stock": 15,
      "precio": 75.00,
      "img": "",
      "provedor": "Mobiliario Clínico Vet"
    },
    {
      "id": 54,
      "nombre": "Gotas Oftálmicas Antibióticas",
      "categoria": "Medicamentos",
      "stock": 90,
      "precio": 12.00,
      "img": "",
      "provedor": "Dermavet Pharma"
    },
    {
      "id": 55,
      "nombre": "Champú Pelo Blanco",
      "categoria": "Higiene",
      "stock": 38,
      "precio": 14.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 56,
      "nombre": "Collar Antipulgas Larga Duración",
      "categoria": "Antiparasitarios",
      "stock": 70,
      "precio": 20.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 57,
      "nombre": "Vacuna Leucemia Felina",
      "categoria": "Vacunas",
      "stock": 45,
      "precio": 31.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 58,
      "nombre": "Suplemento Calcio Cachorros",
      "categoria": "Suplementos",
      "stock": 60,
      "precio": 20.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 59,
      "nombre": "Lámpara Wood Veterinaria",
      "categoria": "Diagnóstico",
      "stock": 3,
      "precio": 180.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 60,
      "nombre": "Monitor Constantes Vitales",
      "categoria": "Equipamiento Médico",
      "stock": 2,
      "precio": 3000.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 61,
      "nombre": "Gasas Parafinadas",
      "categoria": "Material Quirúrgico",
      "stock": 150,
      "precio": 16.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 62,
      "nombre": "Pienso Húmedo Convalecencia (Latas)",
      "categoria": "Alimentos",
      "stock": 180,
      "precio": 4.50,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 63,
      "nombre": "Transportín Gato Homologado",
      "categoria": "Accesorios",
      "stock": 25,
      "precio": 40.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 64,
      "nombre": "Antiinflamatorio Tópico Gel",
      "categoria": "Medicamentos",
      "stock": 80,
      "precio": 17.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 65,
      "nombre": "Acondicionador Pelo Largo",
      "categoria": "Higiene",
      "stock": 30,
      "precio": 12.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 66,
      "nombre": "Tratamiento Ácaros Oído",
      "categoria": "Antiparasitarios",
      "stock": 95,
      "precio": 15.50,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 67,
      "nombre": "Vacuna Rabia Gato",
      "categoria": "Vacunas",
      "stock": 48,
      "precio": 28.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 68,
      "nombre": "Suplemento Piel y Pelo Saludable",
      "categoria": "Suplementos",
      "stock": 70,
      "precio": 27.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 69,
      "nombre": "Centrífuga de Mesa",
      "categoria": "Equipamiento Médico",
      "stock": 1,
      "precio": 600.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 70,
      "nombre": "Test Cistitis Felina",
      "categoria": "Diagnóstico",
      "stock": 20,
      "precio": 65.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 71,
      "nombre": "Sutura Reabsorbible PGA",
      "categoria": "Material Quirúrgico",
      "stock": 50,
      "precio": 20.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 72,
      "nombre": "Pienso Dieta Digestiva Perro",
      "categoria": "Alimentos",
      "stock": 92,
      "precio": 54.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 73,
      "nombre": "Arnés Paseo Anti-tirones",
      "categoria": "Accesorios",
      "stock": 30,
      "precio": 28.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 74,
      "nombre": "Antibiótico Oral Suspensión",
      "categoria": "Medicamentos",
      "stock": 110,
      "precio": 19.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 75,
      "nombre": "Kit Limpieza Dental",
      "categoria": "Higiene",
      "stock": 40,
      "precio": 18.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 76,
      "nombre": "Tabletas Antiparasitarias Gato",
      "categoria": "Antiparasitarios",
      "stock": 100,
      "precio": 9.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 77,
      "nombre": "Vacuna Gripe Canina",
      "categoria": "Vacunas",
      "stock": 52,
      "precio": 27.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 78,
      "nombre": "Calmante Natural Comportamiento",
      "categoria": "Suplementos",
      "stock": 75,
      "precio": 31.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 79,
      "nombre": "Lector Hemogramas Automatizado",
      "categoria": "Equipamiento Médico",
      "stock": 1,
      "precio": 6000.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 80,
      "nombre": "Test Giardia Canina/Felina",
      "categoria": "Diagnóstico",
      "stock": 15,
      "precio": 70.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 81,
      "nombre": "Tubos Vacío Sangre EDTA (Caja)",
      "categoria": "Material Quirúrgico",
      "stock": 20,
      "precio": 12.00,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 82,
      "nombre": "Pienso Hurón Adulto",
      "categoria": "Alimentos",
      "stock": 130,
      "precio": 25.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 83,
      "nombre": "Rascador Gato Poste Grande",
      "categoria": "Accesorios",
      "stock": 10,
      "precio": 55.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 84,
      "nombre": "Solución Ringer Lactato IV (Bolsa)",
      "categoria": "Medicamentos",
      "stock": 150,
      "precio": 6.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 85,
      "nombre": "Secador Pelo Profesional",
      "categoria": "Higiene",
      "stock": 5,
      "precio": 150.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 86,
      "nombre": "Spray Antiparasitario Cama/Hogar",
      "categoria": "Antiparasitarios",
      "stock": 35,
      "precio": 22.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 87,
      "nombre": "Vacuna Herpesvirus Felino",
      "categoria": "Vacunas",
      "stock": 40,
      "precio": 30.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 88,
      "nombre": "Suplemento Renal Gato",
      "categoria": "Suplementos",
      "stock": 68,
      "precio": 40.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 89,
      "nombre": "Equipo Rayos X Portátil",
      "categoria": "Equipamiento Médico",
      "stock": 1,
      "precio": 15000.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 90,
      "nombre": "Test Ehrlichia Canina",
      "categoria": "Diagnóstico",
      "stock": 22,
      "precio": 80.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 91,
      "nombre": "Pinzas Hemostáticas (Set)",
      "categoria": "Material Quirúrgico",
      "stock": 8,
      "precio": 95.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 92,
      "nombre": "Pienso Pescado Océanico Gato",
      "categoria": "Alimentos",
      "stock": 70,
      "precio": 41.00,
      "img": "",
      "provedor": "Felinos Diet"
    },
    {
      "id": 93,
      "nombre": "Abrigo Invierno Impermeable Perro",
      "categoria": "Accesorios",
      "stock": 20,
      "precio": 35.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 94,
      "nombre": "Colirio Humectante Ocular",
      "categoria": "Medicamentos",
      "stock": 105,
      "precio": 9.50,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 95,
      "nombre": "Esquiladora Eléctrica Profesional",
      "categoria": "Higiene",
      "stock": 4,
      "precio": 250.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 96,
      "nombre": "Tabletas Control Gusanos Corazón",
      "categoria": "Antiparasitarios",
      "stock": 85,
      "precio": 18.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 97,
      "nombre": "Vacuna Polivalente Gato",
      "categoria": "Vacunas",
      "stock": 58,
      "precio": 33.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 98,
      "nombre": "Suplemento Multivitamínico Diario",
      "categoria": "Suplementos",
      "stock": 110,
      "precio": 23.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 99,
      "nombre": "Balanza Pediátrica Digital",
      "categoria": "Equipamiento Médico",
      "stock": 6,
      "precio": 120.00,
      "img": "",
      "provedor": "Mobiliario Clínico Vet"
    },
    {
      "id": 100,
      "nombre": "Test Anaplasma Canina",
      "categoria": "Diagnóstico",
      "stock": 18,
      "precio": 82.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 101,
      "nombre": "Hoja de Bisturí #20 (Caja 10)",
      "categoria": "Material Quirúrgico",
      "stock": 38,
      "precio": 9.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 102,
      "nombre": "Pienso Perro Dieta Articular",
      "categoria": "Alimentos",
      "stock": 65,
      "precio": 60.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 103,
      "nombre": "Cama Cueva Felina",
      "categoria": "Accesorios",
      "stock": 28,
      "precio": 30.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 104,
      "nombre": "Jarabe Antitusivo Canino",
      "categoria": "Medicamentos",
      "stock": 70,
      "precio": 16.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 105,
      "nombre": "Cortaúñas Guía Seguridad",
      "categoria": "Higiene",
      "stock": 50,
      "precio": 10.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 106,
      "nombre": "Loción Antiparasitaria Corporal",
      "categoria": "Antiparasitarios",
      "stock": 60,
      "precio": 14.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 107,
      "nombre": "Vacuna Parainfluenza Canina",
      "categoria": "Vacunas",
      "stock": 45,
      "precio": 26.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 108,
      "nombre": "Gel Nutricional Alta Energía",
      "categoria": "Suplementos",
      "stock": 85,
      "precio": 19.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 109,
      "nombre": "Otoscopio Veterinario",
      "categoria": "Equipamiento Médico",
      "stock": 7,
      "precio": 250.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 110,
      "nombre": "Test Leishmaniosis Canina",
      "categoria": "Diagnóstico",
      "stock": 30,
      "precio": 78.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 111,
      "nombre": "Campo Quirúrgico Estéril",
      "categoria": "Material Quirúrgico",
      "stock": 100,
      "precio": 7.00,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 112,
      "nombre": "Pienso Conejo Joven",
      "categoria": "Alimentos",
      "stock": 140,
      "precio": 17.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 113,
      "nombre": "Juguete Interactivo Dispensador",
      "categoria": "Accesorios",
      "stock": 55,
      "precio": 15.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 114,
      "nombre": "Crema Cicatrizante Post-quirúrgica",
      "categoria": "Medicamentos",
      "stock": 60,
      "precio": 21.00,
      "img": "",
      "provedor": "Dermavet Pharma"
    },
    {
      "id": 115,
      "nombre": "Cepillo Goma Masaje",
      "categoria": "Higiene",
      "stock": 70,
      "precio": 8.50,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 116,
      "nombre": "Comprimidos Antiparasitarios Amplio Espectro",
      "categoria": "Antiparasitarios",
      "stock": 120,
      "precio": 10.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 117,
      "nombre": "Vacuna Infección Vías Altas Felina",
      "categoria": "Vacunas",
      "stock": 50,
      "precio": 29.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 118,
      "nombre": "Aceite Salmón Suplemento Piel",
      "categoria": "Suplementos",
      "stock": 80,
      "precio": 26.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 119,
      "nombre": "Bomba Infusión Volumétrica",
      "categoria": "Equipamiento Médico",
      "stock": 2,
      "precio": 1800.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 120,
      "nombre": "Test Coronavirus Felino (FCoV)",
      "categoria": "Diagnóstico",
      "stock": 25,
      "precio": 68.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 121,
      "nombre": "Cinta Adhesiva Quirúrgica",
      "categoria": "Material Quirúrgico",
      "stock": 150,
      "precio": 5.00,
      "img": "",
      "provedor": "Material Quirúrgico Express"
    },
    {
      "id": 122,
      "nombre": "Pienso Cobaya Adulto",
      "categoria": "Alimentos",
      "stock": 170,
      "precio": 16.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 123,
      "nombre": "Bozal Nylon Ajustable",
      "categoria": "Accesorios",
      "stock": 45,
      "precio": 11.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 124,
      "nombre": "Inyectable Corticoide",
      "categoria": "Medicamentos",
      "stock": 50,
      "precio": 35.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 125,
      "nombre": "Champú Pelo Corto",
      "categoria": "Higiene",
      "stock": 42,
      "precio": 13.50,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 126,
      "nombre": "Tabletas Prevención Pulgas Mensual",
      "categoria": "Antiparasitarios",
      "stock": 98,
      "precio": 20.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 127,
      "nombre": "Vacuna Parvovirus Felino",
      "categoria": "Vacunas",
      "stock": 48,
      "precio": 31.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 128,
      "nombre": "Suplemento Soporte Hepático",
      "categoria": "Suplementos",
      "stock": 62,
      "precio": 45.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 129,
      "nombre": "Negatoscopio Led",
      "categoria": "Equipamiento Médico",
      "stock": 3,
      "precio": 300.00,
      "img": "",
      "provedor": "Mobiliario Clínico Vet"
    },
    {
      "id": 130,
      "nombre": "Test Coombs Directo",
      "categoria": "Diagnóstico",
      "stock": 12,
      "precio": 120.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 131,
      "nombre": "Separadores Farabeuf (Par)",
      "categoria": "Material Quirúrgico",
      "stock": 15,
      "precio": 40.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 132,
      "nombre": "Pienso Exóticos Loros",
      "categoria": "Alimentos",
      "stock": 100,
      "precio": 28.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 133,
      "nombre": "Fuente Agua Automática",
      "categoria": "Accesorios",
      "stock": 18,
      "precio": 50.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 134,
      "nombre": "Inmunosupresor Oral",
      "categoria": "Medicamentos",
      "stock": 40,
      "precio": 65.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 135,
      "nombre": "Spray Desenredante",
      "categoria": "Higiene",
      "stock": 55,
      "precio": 10.00,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 136,
      "nombre": "Ampolla Antiparasitaria Interna/Externa",
      "categoria": "Antiparasitarios",
      "stock": 80,
      "precio": 17.00,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 137,
      "nombre": "Vacuna Chlamydophila Felina",
      "categoria": "Vacunas",
      "stock": 35,
      "precio": 30.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 138,
      "nombre": "Suplemento Soporte Comportamiento Ansiedad",
      "categoria": "Suplementos",
      "stock": 70,
      "precio": 38.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 139,
      "nombre": "Autoclave Clase B 23L",
      "categoria": "Equipamiento Médico",
      "stock": 1,
      "precio": 2500.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 140,
      "nombre": "Test moquillo canino",
      "categoria": "Diagnóstico",
      "stock": 15,
      "precio": 75.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    },
    {
      "id": 141,
      "nombre": "Pinza de Biopsia Endoscópica",
      "categoria": "Material Quirúrgico",
      "stock": 10,
      "precio": 150.00,
      "img": "",
      "provedor": "Suturas VetCorp"
    },
    {
      "id": 142,
      "nombre": "Pienso Dieta Hepática Perro",
      "categoria": "Alimentos",
      "stock": 55,
      "precio": 58.00,
      "img": "",
      "provedor": "NutriAnimal Pro"
    },
    {
      "id": 143,
      "nombre": "Ropa Postoperatoria Perro",
      "categoria": "Accesorios",
      "stock": 22,
      "precio": 25.00,
      "img": "",
      "provedor": "Accesorios Animalia"
    },
    {
      "id": 144,
      "nombre": "Fármaco Cardio-respiratorio",
      "categoria": "Medicamentos",
      "stock": 45,
      "precio": 40.00,
      "img": "",
      "provedor": "Farmavet S.L."
    },
    {
      "id": 145,
      "nombre": "Espuma Limpiadora Patas",
      "categoria": "Higiene",
      "stock": 60,
      "precio": 11.50,
      "img": "",
      "provedor": "HigieneVet Total"
    },
    {
      "id": 146,
      "nombre": "Pipeta Control Larvas",
      "categoria": "Antiparasitarios",
      "stock": 88,
      "precio": 16.50,
      "img": "",
      "provedor": "Control Parásitos S.L."
    },
    {
      "id": 147,
      "nombre": "Vacuna Adenovirus Canino Tipo 2",
      "categoria": "Vacunas",
      "stock": 40,
      "precio": 28.00,
      "img": "",
      "provedor": "Vaxani Veterinaria"
    },
    {
      "id": 148,
      "nombre": "Suplemento Control Bolas Pelo",
      "categoria": "Suplementos",
      "stock": 75,
      "precio": 14.00,
      "img": "",
      "provedor": "VetSuplem Innova"
    },
    {
      "id": 149,
      "nombre": "Bomba de Infusión Jeringa",
      "categoria": "Equipamiento Médico",
      "stock": 2,
      "precio": 1500.00,
      "img": "",
      "provedor": "EquipaVet Premium"
    },
    {
      "id": 150,
      "nombre": "Test Leucemia Felina",
      "categoria": "Diagnóstico",
      "stock": 28,
      "precio": 85.00,
      "img": "",
      "provedor": "DiagnosVet Labs"
    }
  ]

export const inventoryMovements = [
  // Example Movement (similar to the one provided)
  {
    id: 1,
    type: "entrada", // Type of movement: 'entrada' (entry) or 'salida' (exit)
    description: "Compra inicial de stock", // Description of the movement
    date: "2024-01-10T08:00:00", // Date and time of the movement (ISO 8601 format)
    quantity: 50, // Quantity of products involved in the movement
    products: ["Antibiótico AmoxiVet 500mg"], // Array of product names involved
    reference: "COMP-2024-001", // Reference code for the movement (e.g., invoice, order number)
  },
  {
    id: 2,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-01-15T10:30:00",
    quantity: 100,
    products: ["Vacuna Canina DHPPiL"],
    reference: "COMP-2024-002",
  },
  {
    id: 3,
    type: "salida",
    description: "Venta a cliente Sr. Pérez",
    date: "2024-01-16T11:05:00",
    quantity: 2,
    products: ["Antibiótico AmoxiVet 500mg"],
    reference: "VENT-2024-001",
  },
  {
    id: 4,
    type: "salida",
    description: "Venta a cliente Sra. Gómez",
    date: "2024-01-17T14:20:00",
    quantity: 5,
    products: ["Vacuna Canina DHPPiL"],
    reference: "VENT-2024-002",
  },
  {
    id: 5,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-01-20T09:15:00",
    quantity: 30,
    products: ["Desparasitante Prazitel Perros"],
    reference: "COMP-2024-003",
  },
  {
    id: 6,
    type: "salida",
    description: "Uso interno para tratamiento",
    date: "2024-01-21T16:00:00",
    quantity: 1,
    products: ["Antibiótico AmoxiVet 500mg"],
    reference: "USO-2024-001",
  },
  {
    id: 7,
    type: "salida",
    description: "Venta a cliente Clínica Animalia",
    date: "2024-01-22T10:00:00",
    quantity: 10,
    products: ["Desparasitante Prazitel Perros"],
    reference: "VENT-2024-003",
  },
  {
    id: 8,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-01-25T11:45:00",
    quantity: 25,
    products: ["Shampoo Medicado Clorhexidina"],
    reference: "COMP-2024-004",
  },
  {
    id: 9,
    type: "salida",
    description: "Venta a cliente Sr. Ramírez",
    date: "2024-01-26T15:30:00",
    quantity: 1,
    products: ["Shampoo Medicado Clorhexidina"],
    reference: "VENT-2024-004",
  },
  {
    id: 10,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-02-01T08:30:00",
    quantity: 40,
    products: ["Alimento Royal Canin Vet Diet Renal Gato"],
    reference: "COMP-2024-005",
  },
  // --- Adding more movements ---
  {
    id: 11,
    type: "salida",
    description: "Venta a cliente Sra. López",
    date: "2024-02-02T12:10:00",
    quantity: 3,
    products: ["Alimento Royal Canin Vet Diet Renal Gato"],
    reference: "VENT-2024-005",
  },
  {
    id: 12,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-02-05T09:00:00",
    quantity: 60,
    products: ["Antibiótico Enrofloxacina 50mg"],
    reference: "COMP-2024-006",
  },
  {
    id: 13,
    type: "salida",
    description: "Uso interno para hospitalización",
    date: "2024-02-06T17:00:00",
    quantity: 4,
    products: ["Antibiótico Enrofloxacina 50mg"],
    reference: "USO-2024-002",
  },
  {
    id: 14,
    type: "salida",
    description: "Venta a cliente Sr. Castillo",
    date: "2024-02-07T11:55:00",
    quantity: 1,
    products: ["Vacuna Canina DHPPiL"],
    reference: "VENT-2024-006",
  },
  {
    id: 15,
    type: "entrada",
    description: "Devolución de cliente Sra. Gómez",
    date: "2024-02-08T10:15:00",
    quantity: 1,
    products: ["Vacuna Canina DHPPiL"],
    reference: "DEV-2024-001",
  },
  {
    id: 16,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-02-10T14:00:00",
    quantity: 20,
    products: ["Analgésico Meloxicam Gotas"],
    reference: "COMP-2024-007",
  },
  {
    id: 17,
    type: "salida",
    description: "Venta a cliente Sra. Díaz",
    date: "2024-02-11T09:45:00",
    quantity: 1,
    products: ["Analgésico Meloxicam Gotas"],
    reference: "VENT-2024-007",
  },
  {
    id: 18,
    type: "salida",
    description: "Ajuste por caducidad",
    date: "2024-02-12T18:00:00",
    quantity: 2,
    products: ["Antibiótico AmoxiVet 500mg"],
    reference: "AJST-2024-001",
  },
  {
    id: 19,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-02-15T11:00:00",
    quantity: 50,
    products: ["Suero Fisiológico 500ml"],
    reference: "COMP-2024-008",
  },
  {
    id: 20,
    type: "salida",
    description: "Uso en cirugía",
    date: "2024-02-16T13:30:00",
    quantity: 3,
    products: ["Suero Fisiológico 500ml"],
    reference: "USO-2024-003",
  },
  {
    id: 21,
    type: "salida",
    description: "Venta a cliente Sr. Vargas",
    date: "2024-02-17T10:20:00",
    quantity: 2,
    products: ["Desparasitante Prazitel Perros"],
    reference: "VENT-2024-008",
  },
  {
    id: 22,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-02-20T09:30:00",
    quantity: 15,
    products: ["Protector Hepático Silimarina"],
    reference: "COMP-2024-009",
  },
  {
    id: 23,
    type: "salida",
    description: "Venta a cliente Sra. Méndez",
    date: "2024-02-21T16:15:00",
    quantity: 1,
    products: ["Protector Hepático Silimarina"],
    reference: "VENT-2024-009",
  },
  {
    id: 24,
    type: "salida",
    description: "Venta a cliente Sr. Silva",
    date: "2024-02-22T11:00:00",
    quantity: 1,
    products: ["Shampoo Medicado Clorhexidina"],
    reference: "VENT-2024-010",
  },
  {
    id: 25,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-02-25T10:45:00",
    quantity: 80,
    products: ["Vacuna Felina Triple"],
    reference: "COMP-2024-010",
  },
  {
    id: 26,
    type: "salida",
    description: "Venta a cliente Sra. Ríos",
    date: "2024-02-26T14:00:00",
    quantity: 3,
    products: ["Vacuna Felina Triple"],
    reference: "VENT-2024-011",
  },
  {
    id: 27,
    type: "salida",
    description: "Venta a cliente Sr. Núñez",
    date: "2024-02-27T09:50:00",
    quantity: 2,
    products: ["Alimento Royal Canin Vet Diet Renal Gato"],
    reference: "VENT-2024-012",
  },
  {
    id: 28,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-03-01T08:15:00",
    quantity: 25,
    products: ["Antiinflamatorio Carprofeno 50mg"],
    reference: "COMP-2024-011",
  },
  {
    id: 29,
    type: "salida",
    description: "Venta a cliente Sra. Mora",
    date: "2024-03-02T11:30:00",
    quantity: 1,
    products: ["Antiinflamatorio Carprofeno 50mg"],
    reference: "VENT-2024-013",
  },
  {
    id: 30,
    type: "salida",
    description: "Uso interno post-operatorio",
    date: "2024-03-03T15:00:00",
    quantity: 2,
    products: ["Antibiótico Enrofloxacina 50mg"],
    reference: "USO-2024-004",
  },
  // ... (Adding 95 more entries to reach ~125)
  {
    id: 31,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-03-05T10:00:00",
    quantity: 40,
    products: ["Pipeta Antipulgas Fipronil Perro Mediano"],
    reference: "COMP-2024-012",
  },
  {
    id: 32,
    type: "salida",
    description: "Venta a cliente Sr. Torres",
    date: "2024-03-06T14:25:00",
    quantity: 2,
    products: ["Pipeta Antipulgas Fipronil Perro Mediano"],
    reference: "VENT-2024-014",
  },
  {
    id: 33,
    type: "salida",
    description: "Venta a cliente Sra. Vega",
    date: "2024-03-07T09:10:00",
    quantity: 1,
    products: ["Analgésico Meloxicam Gotas"],
    reference: "VENT-2024-015",
  },
  {
    id: 34,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-03-10T11:15:00",
    quantity: 10,
    products: ["Alimento Hill's Prescription Diet k/d Gato"],
    reference: "COMP-2024-013",
  },
  {
    id: 35,
    type: "salida",
    description: "Venta a cliente Sr. Romero",
    date: "2024-03-11T16:40:00",
    quantity: 1,
    products: ["Alimento Hill's Prescription Diet k/d Gato"],
    reference: "VENT-2024-016",
  },
  {
    id: 36,
    type: "salida",
    description: "Uso en consulta",
    date: "2024-03-12T10:50:00",
    quantity: 5,
    products: ["Suero Fisiológico 500ml"],
    reference: "USO-2024-005",
  },
  {
    id: 37,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-03-15T08:45:00",
    quantity: 30,
    products: ["Gotas Óticas Antibióticas/Antiinflamatorias"],
    reference: "COMP-2024-014",
  },
  {
    id: 38,
    type: "salida",
    description: "Venta a cliente Sra. Peña",
    date: "2024-03-16T12:00:00",
    quantity: 1,
    products: ["Gotas Óticas Antibióticas/Antiinflamatorias"],
    reference: "VENT-2024-017",
  },
  {
    id: 39,
    type: "salida",
    description: "Venta a cliente Sr. Blanco",
    date: "2024-03-17T15:15:00",
    quantity: 1,
    products: ["Protector Hepático Silimarina"],
    reference: "VENT-2024-018",
  },
  {
    id: 40,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-03-20T09:55:00",
    quantity: 70,
    products: ["Vacuna Canina Rabia"],
    reference: "COMP-2024-015",
  },
   {
    id: 41,
    type: "salida",
    description: "Campaña de vacunación",
    date: "2024-03-21T10:00:00",
    quantity: 15,
    products: ["Vacuna Canina Rabia"],
    reference: "CAMP-2024-001",
  },
  {
    id: 42,
    type: "salida",
    description: "Venta a cliente Sra. Soto",
    date: "2024-03-22T11:20:00",
    quantity: 1,
    products: ["Vacuna Canina Rabia"],
    reference: "VENT-2024-019",
  },
  {
    id: 43,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-03-25T14:10:00",
    quantity: 20,
    products: ["Cicatrizante en Spray Plata"],
    reference: "COMP-2024-016",
  },
  {
    id: 44,
    type: "salida",
    description: "Uso en curación",
    date: "2024-03-26T16:05:00",
    quantity: 1,
    products: ["Cicatrizante en Spray Plata"],
    reference: "USO-2024-006",
  },
  {
    id: 45,
    type: "salida",
    description: "Venta a cliente Sr. Herrera",
    date: "2024-03-27T09:35:00",
    quantity: 1,
    products: ["Antiinflamatorio Carprofeno 50mg"],
    reference: "VENT-2024-020",
  },
  {
    id: 46,
    type: "entrada",
    description: "Compra a proveedor PharmaVet",
    date: "2024-03-30T10:30:00",
    quantity: 50,
    products: ["Antibiótico Doxiciclina 100mg"],
    reference: "COMP-2024-017",
  },
  {
    id: 47,
    type: "salida",
    description: "Venta a cliente Clínica San Roque",
    date: "2024-04-01T11:00:00",
    quantity: 10,
    products: ["Antibiótico Doxiciclina 100mg"],
    reference: "VENT-2024-021",
  },
  {
    id: 48,
    type: "salida",
    description: "Venta a cliente Sra. Luna",
    date: "2024-04-02T15:45:00",
    quantity: 1,
    products: ["Pipeta Antipulgas Fipronil Perro Mediano"],
    reference: "VENT-2024-022",
  },
  {
    id: 49,
    type: "entrada",
    description: "Compra a proveedor VetSupplies",
    date: "2024-04-05T09:20:00",
    quantity: 15,
    products: ["Suplemento Articular Condroitina/Glucosamina"],
    reference: "COMP-2024-018",
  },
  {
    id: 50,
    type: "salida",
    description: "Venta a cliente Sr. Medina",
    date: "2024-04-06T12:15:00",
    quantity: 1,
    products: ["Suplemento Articular Condroitina/Glucosamina"],
    reference: "VENT-2024-023",
  },
  // --- Continue adding entries ---
  // ... (Generating more entries up to ~125)
  { id: 51, type: "salida", description: "Venta a cliente Sra. Campos", date: "2024-04-07T10:05:00", quantity: 1, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "VENT-2024-024" },
  { id: 52, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-04-10T11:50:00", quantity: 35, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "COMP-2024-019" },
  { id: 53, type: "salida", description: "Venta a cliente Sr. Osorio", date: "2024-04-11T14:30:00", quantity: 3, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "VENT-2024-025" },
  { id: 54, type: "salida", description: "Ajuste por rotura", date: "2024-04-12T17:45:00", quantity: 1, products: ["Suero Fisiológico 500ml"], reference: "AJST-2024-002" },
  { id: 55, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-04-15T09:00:00", quantity: 25, products: ["Antibiótico Cefalexina 500mg"], reference: "COMP-2024-020" },
  { id: 56, type: "salida", description: "Venta a cliente Sra. Paredes", date: "2024-04-16T10:40:00", quantity: 1, products: ["Antibiótico Cefalexina 500mg"], reference: "VENT-2024-026" },
  { id: 57, type: "salida", description: "Uso interno", date: "2024-04-17T16:20:00", quantity: 1, products: ["Gotas Óticas Antibióticas/Antiinflamatorias"], reference: "USO-2024-007" },
  { id: 58, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-04-20T13:10:00", quantity: 10, products: ["Alimento Royal Canin Vet Diet Urinary SO Perro"], reference: "COMP-2024-021" },
  { id: 59, type: "salida", description: "Venta a cliente Sr. Franco", date: "2024-04-21T11:00:00", quantity: 2, products: ["Alimento Royal Canin Vet Diet Urinary SO Perro"], reference: "VENT-2024-027" },
  { id: 60, type: "salida", description: "Venta a cliente Sra. Pinto", date: "2024-04-22T15:00:00", quantity: 1, products: ["Vacuna Canina Rabia"], reference: "VENT-2024-028" },
  { id: 61, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-04-25T08:30:00", quantity: 60, products: ["Desparasitante Interno Febendazol Suspensión"], reference: "COMP-2024-022" },
  { id: 62, type: "salida", description: "Venta a criadero CanFeliz", date: "2024-04-26T10:15:00", quantity: 5, products: ["Desparasitante Interno Febendazol Suspensión"], reference: "VENT-2024-029" },
  { id: 63, type: "salida", description: "Venta a cliente Sr. Solis", date: "2024-04-27T14:55:00", quantity: 1, products: ["Cicatrizante en Spray Plata"], reference: "VENT-2024-030" },
  { id: 64, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-04-30T11:25:00", quantity: 20, products: ["Vitaminas Complejo B Inyectable"], reference: "COMP-2024-023" },
  { id: 65, type: "salida", description: "Uso en tratamiento anemia", date: "2024-05-01T16:30:00", quantity: 2, products: ["Vitaminas Complejo B Inyectable"], reference: "USO-2024-008" },
  { id: 66, type: "salida", description: "Venta a cliente Sra. Bravo", date: "2024-05-02T09:40:00", quantity: 1, products: ["Antibiótico Doxiciclina 100mg"], reference: "VENT-2024-031" },
  { id: 67, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-05-05T10:00:00", quantity: 30, products: ["Shampoo Antipulgas Permetrina"], reference: "COMP-2024-024" },
  { id: 68, type: "salida", description: "Venta a cliente Sr. Reyes", date: "2024-05-06T13:05:00", quantity: 1, products: ["Shampoo Antipulgas Permetrina"], reference: "VENT-2024-032" },
  { id: 69, type: "salida", description: "Venta a cliente Sra. Gil", date: "2024-05-07T15:20:00", quantity: 1, products: ["Suplemento Articular Condroitina/Glucosamina"], reference: "VENT-2024-033" },
  { id: 70, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-05-10T08:50:00", quantity: 45, products: ["Antibiótico AmoxiVet 500mg"], reference: "COMP-2024-025" },
  { id: 71, type: "salida", description: "Venta a cliente Sr. León", date: "2024-05-11T11:10:00", quantity: 3, products: ["Antibiótico AmoxiVet 500mg"], reference: "VENT-2024-034" },
  { id: 72, type: "salida", description: "Venta a cliente Sra. Cruz", date: "2024-05-12T14:40:00", quantity: 2, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "VENT-2024-035" },
  { id: 73, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-05-15T09:30:00", quantity: 90, products: ["Vacuna Canina DHPPiL"], reference: "COMP-2024-026" },
  { id: 74, type: "salida", description: "Venta a cliente Sr. Marin", date: "2024-05-16T10:25:00", quantity: 4, products: ["Vacuna Canina DHPPiL"], reference: "VENT-2024-036" },
  { id: 75, type: "salida", description: "Venta a cliente Sra. Ortiz", date: "2024-05-17T16:00:00", quantity: 1, products: ["Antibiótico Cefalexina 500mg"], reference: "VENT-2024-037" },
  { id: 76, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-05-20T11:00:00", quantity: 20, products: ["Desparasitante Prazitel Perros"], reference: "COMP-2024-027" },
  { id: 77, type: "salida", description: "Venta a cliente Sr. Castro", date: "2024-05-21T13:45:00", quantity: 2, products: ["Desparasitante Prazitel Perros"], reference: "VENT-2024-038" },
  { id: 78, type: "salida", description: "Uso interno", date: "2024-05-22T17:10:00", quantity: 1, products: ["Alimento Royal Canin Vet Diet Urinary SO Perro"], reference: "USO-2024-009" },
  { id: 79, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-05-25T09:15:00", quantity: 30, products: ["Shampoo Medicado Clorhexidina"], reference: "COMP-2024-028" },
  { id: 80, type: "salida", description: "Venta a cliente Sra. Rubio", date: "2024-05-26T10:50:00", quantity: 1, products: ["Shampoo Medicado Clorhexidina"], reference: "VENT-2024-039" },
  { id: 81, type: "salida", description: "Venta a cliente Sr. Navarro", date: "2024-05-27T14:00:00", quantity: 3, products: ["Desparasitante Interno Febendazol Suspensión"], reference: "VENT-2024-040" },
  { id: 82, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-05-30T10:40:00", quantity: 35, products: ["Alimento Royal Canin Vet Diet Renal Gato"], reference: "COMP-2024-029" },
  { id: 83, type: "salida", description: "Venta a cliente Sra. Iglesias", date: "2024-06-01T11:55:00", quantity: 2, products: ["Alimento Royal Canin Vet Diet Renal Gato"], reference: "VENT-2024-041" },
  { id: 84, type: "salida", description: "Uso en hospitalización", date: "2024-06-02T16:45:00", quantity: 1, products: ["Vitaminas Complejo B Inyectable"], reference: "USO-2024-010" },
  { id: 85, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-06-05T08:20:00", quantity: 55, products: ["Antibiótico Enrofloxacina 50mg"], reference: "COMP-2024-030" },
  { id: 86, type: "salida", description: "Venta a cliente Sr. Cano", date: "2024-06-06T10:30:00", quantity: 2, products: ["Antibiótico Enrofloxacina 50mg"], reference: "VENT-2024-042" },
  { id: 87, type: "salida", description: "Venta a cliente Sra. Aguilar", date: "2024-06-07T13:15:00", quantity: 1, products: ["Shampoo Antipulgas Permetrina"], reference: "VENT-2024-043" },
  { id: 88, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-06-10T09:05:00", quantity: 18, products: ["Analgésico Meloxicam Gotas"], reference: "COMP-2024-031" },
  { id: 89, type: "salida", description: "Venta a cliente Sr. Parra", date: "2024-06-11T12:00:00", quantity: 1, products: ["Analgésico Meloxicam Gotas"], reference: "VENT-2024-044" },
  { id: 90, type: "salida", description: "Ajuste por caducidad", date: "2024-06-12T18:10:00", quantity: 1, products: ["Vacuna Felina Triple"], reference: "AJST-2024-003" },
  { id: 91, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-06-15T11:35:00", quantity: 40, products: ["Suero Fisiológico 500ml"], reference: "COMP-2024-032" },
  { id: 92, type: "salida", description: "Uso en cirugía", date: "2024-06-16T14:00:00", quantity: 2, products: ["Suero Fisiológico 500ml"], reference: "USO-2024-011" },
  { id: 93, type: "salida", description: "Venta a cliente Sra. Molina", date: "2024-06-17T09:50:00", quantity: 1, products: ["Antibiótico AmoxiVet 500mg"], reference: "VENT-2024-045" },
  { id: 94, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-06-20T10:10:00", quantity: 12, products: ["Protector Hepático Silimarina"], reference: "COMP-2024-033" },
  { id: 95, type: "salida", description: "Venta a cliente Sr. Delgado", date: "2024-06-21T15:05:00", quantity: 1, products: ["Protector Hepático Silimarina"], reference: "VENT-2024-046" },
  { id: 96, type: "salida", description: "Venta a cliente Sra. Santana", date: "2024-06-22T11:40:00", quantity: 2, products: ["Vacuna Canina DHPPiL"], reference: "VENT-2024-047" },
  { id: 97, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-06-25T08:55:00", quantity: 75, products: ["Vacuna Felina Triple"], reference: "COMP-2024-034" },
  { id: 98, type: "salida", description: "Venta a cliente Sr. Vidal", date: "2024-06-26T10:00:00", quantity: 2, products: ["Vacuna Felina Triple"], reference: "VENT-2024-048" },
  { id: 99, type: "salida", description: "Venta a cliente Sra. Rojas", date: "2024-06-27T14:20:00", quantity: 1, products: ["Desparasitante Prazitel Perros"], reference: "VENT-2024-049" },
  { id: 100, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-06-30T09:25:00", quantity: 22, products: ["Antiinflamatorio Carprofeno 50mg"], reference: "COMP-2024-035" },
  { id: 101, type: "salida", description: "Venta a cliente Sr. Ortega", date: "2024-07-01T11:15:00", quantity: 1, products: ["Antiinflamatorio Carprofeno 50mg"], reference: "VENT-2024-050" },
  { id: 102, type: "salida", description: "Uso interno", date: "2024-07-02T16:50:00", quantity: 1, products: ["Antibiótico Enrofloxacina 50mg"], reference: "USO-2024-012" },
  { id: 103, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-07-05T10:35:00", quantity: 38, products: ["Pipeta Antipulgas Fipronil Perro Mediano"], reference: "COMP-2024-036" },
  { id: 104, type: "salida", description: "Venta a cliente Sra. Serrano", date: "2024-07-06T13:30:00", quantity: 2, products: ["Pipeta Antipulgas Fipronil Perro Mediano"], reference: "VENT-2024-051" },
  { id: 105, type: "salida", description: "Venta a cliente Sr. Duran", date: "2024-07-07T09:00:00", quantity: 1, products: ["Analgésico Meloxicam Gotas"], reference: "VENT-2024-052" },
  { id: 106, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-07-10T11:05:00", quantity: 8, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "COMP-2024-037" },
  { id: 107, type: "salida", description: "Venta a cliente Sra. Flores", date: "2024-07-11T15:55:00", quantity: 1, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "VENT-2024-053" },
  { id: 108, type: "salida", description: "Uso en consulta", date: "2024-07-12T10:10:00", quantity: 3, products: ["Suero Fisiológico 500ml"], reference: "USO-2024-013" },
  { id: 109, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-07-15T08:40:00", quantity: 28, products: ["Gotas Óticas Antibióticas/Antiinflamatorias"], reference: "COMP-2024-038" },
  { id: 110, type: "salida", description: "Venta a cliente Sr. Acosta", date: "2024-07-16T12:25:00", quantity: 1, products: ["Gotas Óticas Antibióticas/Antiinflamatorias"], reference: "VENT-2024-054" },
  { id: 111, type: "salida", description: "Venta a cliente Sra. Benitez", date: "2024-07-17T14:50:00", quantity: 1, products: ["Protector Hepático Silimarina"], reference: "VENT-2024-055" },
  { id: 112, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-07-20T09:45:00", quantity: 65, products: ["Vacuna Canina Rabia"], reference: "COMP-2024-039" },
  { id: 113, type: "salida", description: "Campaña de vacunación", date: "2024-07-21T10:15:00", quantity: 12, products: ["Vacuna Canina Rabia"], reference: "CAMP-2024-002" },
  { id: 114, type: "salida", description: "Venta a cliente Sr. Cabrera", date: "2024-07-22T11:30:00", quantity: 1, products: ["Vacuna Canina Rabia"], reference: "VENT-2024-056" },
  { id: 115, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-07-25T13:50:00", quantity: 18, products: ["Cicatrizante en Spray Plata"], reference: "COMP-2024-040" },
  { id: 116, type: "salida", description: "Uso en curación", date: "2024-07-26T16:10:00", quantity: 1, products: ["Cicatrizante en Spray Plata"], reference: "USO-2024-014" },
  { id: 117, type: "salida", description: "Venta a cliente Sra. Dominguez", date: "2024-07-27T09:20:00", quantity: 1, products: ["Antiinflamatorio Carprofeno 50mg"], reference: "VENT-2024-057" },
  { id: 118, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-07-30T10:05:00", quantity: 45, products: ["Antibiótico Doxiciclina 100mg"], reference: "COMP-2024-041" },
  { id: 119, type: "salida", description: "Venta a cliente Clínica VetSur", date: "2024-08-01T11:20:00", quantity: 8, products: ["Antibiótico Doxiciclina 100mg"], reference: "VENT-2024-058" },
  { id: 120, type: "salida", description: "Venta a cliente Sr. Espinoza", date: "2024-08-02T15:35:00", quantity: 1, products: ["Pipeta Antipulgas Fipronil Perro Mediano"], reference: "VENT-2024-059" },
  { id: 121, type: "entrada", description: "Compra a proveedor VetSupplies", date: "2024-08-05T09:10:00", quantity: 14, products: ["Suplemento Articular Condroitina/Glucosamina"], reference: "COMP-2024-042" },
  { id: 122, type: "salida", description: "Venta a cliente Sra. Fernandez", date: "2024-08-06T12:45:00", quantity: 1, products: ["Suplemento Articular Condroitina/Glucosamina"], reference: "VENT-2024-060" },
  { id: 123, type: "salida", description: "Venta a cliente Sr. Gallardo", date: "2024-08-07T10:20:00", quantity: 1, products: ["Alimento Hill's Prescription Diet k/d Gato"], reference: "VENT-2024-061" },
  { id: 124, type: "entrada", description: "Compra a proveedor PharmaVet", date: "2024-08-10T11:40:00", quantity: 32, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "COMP-2024-043" },
  { id: 125, type: "salida", description: "Venta a cliente Sra. Herrera", date: "2024-08-11T14:05:00", quantity: 2, products: ["Pipeta Antipulgas Selamectina Gato"], reference: "VENT-2024-062" },

];

